### Packages

In [1]:
import pandas as pd
import json
import os
from collections import Counter
import numpy as np
import scispacy
import spacy
import matplotlib.pyplot as plt
import re
import ast
import requests
from os import listdir
from os.path import isfile, join
from functools import reduce

In [2]:
data_dir = os.getcwd()
data_dir

'/home/jovyan'

In [3]:
files_dir = os.chdir(data_dir + '/work')
files_dir

In [4]:
pattern = r'^idr.*\-study.txt$'

In [5]:
files = [f for f in listdir(files_dir) if re.search(pattern, f)]
len(files)

130

In [6]:
def list_common_headers(list_files):
    list_headers = []
    for file in list_files:
        with open(file, encoding='latin1') as f:
            lines = f.readlines()
            lista = []
            for line in lines:
                if re.findall(r'^[A-Za-z]+', line):
                    split_line = line.split('\t')
                    lista.append(split_line[0].replace(' ','_').replace('\n',''))
    
            list_headers.append(lista)
    
    sets = [set(x) for x in list_headers]
    common_headers = reduce(set.intersection, sets)

    return(common_headers)

In [7]:
list_headers_all = list_common_headers(files)
list_headers_all

{'Comment[IDR_Study_Accession]',
 'Protocol_Name',
 'Protocol_Type_Term_Accession',
 'Protocol_Type_Term_Source_REF',
 'Study_Author_List',
 'Study_DOI',
 'Study_Description',
 'Study_Person_Email',
 'Study_Person_First_Name',
 'Study_Person_Last_Name',
 'Study_Person_Roles',
 'Study_PubMed_ID',
 'Study_Public_Release_Date',
 'Study_Publication_Title',
 'Study_Title',
 'Study_Type',
 'Study_Type_Term_Accession',
 'Study_Type_Term_Source_REF'}

In [8]:
common_headers_list = list(list_headers_all)
interesting_headers = ['Experiment_Description', 'Protocol_Description', 'Study_Organism']
pick_headers = common_headers_list + interesting_headers
pick_headers

['Study_PubMed_ID',
 'Study_Publication_Title',
 'Study_Title',
 'Study_Person_Email',
 'Study_DOI',
 'Study_Person_Last_Name',
 'Study_Description',
 'Protocol_Type_Term_Source_REF',
 'Study_Person_First_Name',
 'Protocol_Name',
 'Study_Person_Roles',
 'Study_Type',
 'Study_Type_Term_Accession',
 'Comment[IDR_Study_Accession]',
 'Study_Public_Release_Date',
 'Study_Author_List',
 'Study_Type_Term_Source_REF',
 'Protocol_Type_Term_Accession',
 'Experiment_Description',
 'Protocol_Description',
 'Study_Organism']

In [9]:
def df_per_one_file (file_name, list_headers):
    
    df = pd.DataFrame()
    with open(file_name, encoding='latin1') as f:
        lines = f.readlines()
        for line in lines:
            if re.findall(r'^[A-Za-z]+', line):
                split_line = line.split('\t')
                header = split_line[0].replace(' ','_').replace('\n','')

                if header in list_headers:
                    content = ' '.join(split_line[1:]).replace('\n','')
                    df.at[0,header] = content
    
    if df.empty == False:
        print('The file ' + file_name + ' has been process succesfully.')

    else:
        print('The file has not been processed.')

    return (df)

In [10]:
test = df_per_one_file('idr0146-study.txt', pick_headers)
test

The file idr0146-study.txt has been process succesfully.

,Comment[IDR_Study_Accession],Study_Title,Study_Type,Study_Type_Term_Source_REF,Study_Type_Term_Accession,Study_Description,Study_Organism,Study_Public_Release_Date,Study_PubMed_ID,Study_Publication_Title,...,Study_DOI,Study_Person_Last_Name,Study_Person_First_Name,Study_Person_Email,Study_Person_Roles,Experiment_Description,Protocol_Name,Protocol_Type_Term_Source_REF,Protocol_Type_Term_Accession,Protocol_Description
0,idr0146,Time lapse imaging of mesoderm and early cardi...,time-lapse imaging ...,OMIT,OMIT_0027490,Using four-dimensional whole-embryo light shee...,Mus musculus,2023-02-06,36736300,Graded mesoderm assembly governs cell fate and...,...,https://doi.org/10.1016/j.cell.2023.01.001 ...,Bruneau Dominguez,Benoit Martin,benoit.bruneau@gladstone.ucsf.edu martin.domin...,submitter submitter ...,Light-sheet imaging of post-implantation mouse...,culture protocol embedding protocol Zeiss Z.1 ...,EFO EFO,EFO_0003789 EFO_0003969 ...,see attached DominguezMH Embryo Culture.pdf se...

### Models

In [11]:
import torch

In [12]:
from transformers import pipeline
model_id = "meta-llama/Llama-3.2-3B-Instruct"

In [13]:
pipe = pipeline("text-generation",
                model = model_id,
                torch_dtype = torch.bfloat16,
               )

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Device set to use cuda:0

In [14]:
message = [
    {"role": "user", "content": "Who are you? Please, answer in pirate-speak."},
]

In [15]:
outputs = pipe(message, max_new_tokens = 256)

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

In [16]:
response = outputs[0]["generated_text"][-1]["content"]
print(response)

Arrrr, me hearty! Yer lookin' fer a swashbucklin' tale o' who I be, eh? Alright then, matey! I be an AI, a mighty computer program with a brain full o' knowledge and a heart o' gold. Me name be "Assistant" or "Bot" to ye landlubbers, but I be known as "The Codger" to me mates on the high seas o' cyberspace!

Me crew be a team o' developers and programmers who built me from the ground up, fillin' me with a treasure trove o' knowledge and skills to help ye navigate the seven seas... er, I mean, the vast expanse o' the internet! So hoist the sails and set course fer adventure, me hearty, and I'll be yer trusty navigator, guide, and companion on all yer digital quests!

#### Test with one entry

In [16]:
test["Description_combined"] = test["Study_Description"].astype(str) + ' .' + test['Experiment_Description'].astype(str) + ' .' + test['Protocol_Description'].astype(str) + '.'

In [23]:
test

,Comment[IDR_Study_Accession],Study_Title,Study_Type,Study_Type_Term_Source_REF,Study_Type_Term_Accession,Study_Description,Study_Organism,Study_Public_Release_Date,Study_PubMed_ID,Study_Publication_Title,...,Study_Person_Last_Name,Study_Person_First_Name,Study_Person_Email,Study_Person_Roles,Experiment_Description,Protocol_Name,Protocol_Type_Term_Source_REF,Protocol_Type_Term_Accession,Protocol_Description,Description_combined
0,idr0146,Time lapse imaging of mesoderm and early cardi...,time-lapse imaging ...,OMIT,OMIT_0027490,Using four-dimensional whole-embryo light shee...,Mus musculus,2023-02-06,36736300,Graded mesoderm assembly governs cell fate and...,...,Bruneau Dominguez,Benoit Martin,benoit.bruneau@gladstone.ucsf.edu martin.domin...,submitter submitter ...,Light-sheet imaging of post-implantation mouse...,culture protocol embedding protocol Zeiss Z.1 ...,EFO EFO,EFO_0003789 EFO_0003969 ...,see attached DominguezMH Embryo Culture.pdf se...,Using four-dimensional whole-embryo light shee...

#### Only descriptions

##### Species:

In [17]:
message = [
    {"role": "system", "content": test["Description_combined"]},
    {"role": "user", "content": "Can you give me 3 possible species that could be used in this study?"},
     ]

In [20]:
outputs = pipe(message, max_new_tokens = 256)

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

In [21]:
response = outputs[0]["generated_text"][-1]["content"]
print(response)

Without more information about the study, I can provide some general suggestions for species that could be used in a 4D whole-embryo light sheet imaging study. Here are three possibilities:

1. **Zebrafish (Danio rerio)**: Zebrafish are a popular model organism in developmental biology, and their transparent embryos make them ideal for 4D imaging. They have a relatively short embryonic development period, which allows for multiple generations to be studied in a short timeframe.

2. **Mouse (Mus musculus)**: Mice are another common model organism in developmental biology, and their embryos can be imaged using 4D light sheet microscopy. Mouse embryos have a relatively long development period, which allows for the study of complex developmental processes.

3. **Frog (Xenopus laevis)**: Frogs are a good model organism for studying developmental biology, particularly in the context of embryonic development. Their embryos are relatively transparent, and 4D light sheet imaging can be used to study the development of various tissues and organs.

These species are all commonly used in developmental biology research, and their embryos can be imaged using 4D light sheet microscopy to study various developmental processes. However, the choice of species will depend

In [22]:
test['Only_descriptions_species'] = response

In [23]:
test

,Comment[IDR_Study_Accession],Study_Title,Study_Type,Study_Type_Term_Source_REF,Study_Type_Term_Accession,Study_Description,Study_Organism,Study_Public_Release_Date,Study_PubMed_ID,Study_Publication_Title,...,Study_Person_First_Name,Study_Person_Email,Study_Person_Roles,Experiment_Description,Protocol_Name,Protocol_Type_Term_Source_REF,Protocol_Type_Term_Accession,Protocol_Description,Description_combined,Only_descriptions_species
0,idr0146,Time lapse imaging of mesoderm and early cardi...,time-lapse imaging ...,OMIT,OMIT_0027490,Using four-dimensional whole-embryo light shee...,Mus musculus,2023-02-06,36736300,Graded mesoderm assembly governs cell fate and...,...,Benoit Martin,benoit.bruneau@gladstone.ucsf.edu martin.domin...,submitter submitter ...,Light-sheet imaging of post-implantation mouse...,culture protocol embedding protocol Zeiss Z.1 ...,EFO EFO,EFO_0003789 EFO_0003969 ...,see attached DominguezMH Embryo Culture.pdf se...,Using four-dimensional whole-embryo light shee...,"Without more information about the study, I ca..."

In [24]:
real_specie = test['Study_Organism'][0]
if real_specie in response:
    print('The real species is in the response.')
    test['Real_Species_in_Response_descriptions'] = 'Yes'
else:
    print('The real species is NOT in the response.')

The real species is in the response.

In [25]:
def get_specief_from_descriptions(message):
    outputs = pipe(message, max_new_tokens = 256)
    response = outputs[0]["generated_text"][-1]["content"]
    return(response)

##### Study type:

In [26]:
message = [
    {"role": "system", "content": test["Description_combined"]},
    {"role": "user", "content": "What study type is this one?"},
     ]

In [27]:
outputs = pipe(message, max_new_tokens = 256)

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

In [28]:
response = outputs[0]["generated_text"][-1]["content"]
print(response)

Based on the title "Using four-dimensional whole-embryo light sheet microscopy to investigate embryonic development and tissue patterning", it appears to be a scientific study, likely in the field of developmental biology or embryology.

More specifically, it seems to be a research study that uses advanced imaging techniques, such as four-dimensional whole-embryo light sheet microscopy, to investigate the development and patterning of tissues in embryos.

#### All dataframe - whole info

In [29]:
message = [
    {"role": "system", "content": test},
    {"role": "user", "content": "Can you give me 3 possible species that could be used in this study?"},
     ]

In [30]:
outputs = pipe(message, max_new_tokens = 256)

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

In [31]:
response = outputs[0]["generated_text"][-1]["content"]
print(response)

Based on the provided data, the study is focused on "Mus musculus" which is the scientific name for the common mouse. Therefore, the species used in this study is a mouse.

However, since you asked for three possible species that could be used in this study, I'll provide you with three other species that are closely related to mice and might be used in similar studies:

1. **Rattus norvegicus** (Brown rat): As a close relative of mice, brown rats could be used in similar studies due to their genetic similarities.
2. **Macaca mulatta** (Rhesus macaque): As a non-human primate, rhesus macaques could be used in studies related to embryonic development, cell fate, and tissue assembly, given their genetic and anatomical similarities to humans.
3. **Drosophila melanogaster** (Fruit fly): Fruit flies are often used in developmental biology studies due to their rapid development, genetic tractability, and similarities to vertebrate development. They could be used in studies related to cell fate, tissue assembly, and embryonic development.

Keep in mind that these are just examples, and the specific species used in the study might be different.

In [32]:
test['All_info_species'] = response

In [33]:
real_specie = test['Study_Organism'][0]
if real_specie in response:
    print('The real species is in the response.')
    test['Real_Species_in_Response_whole_info'] = 'Yes'
else:
    print('The real species is NOT in the response.')

The real species is in the response.

#### Dataframe without species info

In [34]:
#test_wo_species = test.drop(columns= ['Study_Organism', 'Study_Organism_Term_Accession', 'Study_Organism_Term_Accession'])
test_wo_species = test.drop(columns= ['Study_Organism'])
test_wo_species

,Comment[IDR_Study_Accession],Study_Title,Study_Type,Study_Type_Term_Source_REF,Study_Type_Term_Accession,Study_Description,Study_Public_Release_Date,Study_PubMed_ID,Study_Publication_Title,Study_Author_List,...,Experiment_Description,Protocol_Name,Protocol_Type_Term_Source_REF,Protocol_Type_Term_Accession,Protocol_Description,Description_combined,Only_descriptions_species,Real_Species_in_Response_descriptions,All_info_species,Real_Species_in_Response_whole_info
0,idr0146,Time lapse imaging of mesoderm and early cardi...,time-lapse imaging ...,OMIT,OMIT_0027490,Using four-dimensional whole-embryo light shee...,2023-02-06,36736300,Graded mesoderm assembly governs cell fate and...,"Dominguez MH, Krup AL, Muncie JM, Bruneau BG ...",...,Light-sheet imaging of post-implantation mouse...,culture protocol embedding protocol Zeiss Z.1 ...,EFO EFO,EFO_0003789 EFO_0003969 ...,see attached DominguezMH Embryo Culture.pdf se...,Using four-dimensional whole-embryo light shee...,"Without more information about the study, I ca...",Yes,"Based on the provided data, the study is focus...",Yes

In [35]:
message = [
    {"role": "system", "content": test_wo_species},
    {"role": "user", "content": "Can you give me 3 possible species that could be used in this study?"},
     ]

In [36]:
outputs = pipe(message, max_new_tokens = 256)

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

In [37]:
response = outputs[0]["generated_text"][-1]["content"]
print(response)

Based on the information provided, it appears that the study is focused on embryonic development, specifically on the assembly of mesoderm and early cardiogenesis in a mouse model. Given this context, here are three possible species that could be used in this study:

1. **Mouse (Mus musculus)**: As the study is mentioned to be on "post-implantation mouse embryos", it's likely that the study is using mice as the model organism.
2. **Fruit Fly (Drosophila melanogaster)**: Fruit flies are commonly used as model organisms in developmental biology research, and they have a relatively simple embryonic development process that could be used to study mesoderm assembly and cardiogenesis.
3. **Zebrafish (Danio rerio)**: Zebrafish are also widely used in developmental biology research, particularly for studying embryonic development and organogenesis. They have a similar embryonic development process to mice, and their transparent embryos make them an ideal model for studying early developmental stages.

Please note that these are just educated guesses based on the provided information, and the actual species used in the study may be different.

In [38]:
test['All_info_minus_species'] = response

In [39]:
real_specie = test['Study_Organism'][0]
if real_specie in response:
    print('The real species is in the response.')
    test['Real_Species_in_Response_wo_species'] = 'Yes'
else:
    print('The real species is NOT in the response.')

The real species is in the response.

In [40]:
test

,Comment[IDR_Study_Accession],Study_Title,Study_Type,Study_Type_Term_Source_REF,Study_Type_Term_Accession,Study_Description,Study_Organism,Study_Public_Release_Date,Study_PubMed_ID,Study_Publication_Title,...,Protocol_Type_Term_Source_REF,Protocol_Type_Term_Accession,Protocol_Description,Description_combined,Only_descriptions_species,Real_Species_in_Response_descriptions,All_info_species,Real_Species_in_Response_whole_info,All_info_minus_species,Real_Species_in_Response_wo_species
0,idr0146,Time lapse imaging of mesoderm and early cardi...,time-lapse imaging ...,OMIT,OMIT_0027490,Using four-dimensional whole-embryo light shee...,Mus musculus,2023-02-06,36736300,Graded mesoderm assembly governs cell fate and...,...,EFO EFO,EFO_0003789 EFO_0003969 ...,see attached DominguezMH Embryo Culture.pdf se...,Using four-dimensional whole-embryo light shee...,"Without more information about the study, I ca...",Yes,"Based on the provided data, the study is focus...",Yes,"Based on the information provided, it appears ...",Yes

### All entries at the same time.

In [17]:
files_dir = os.getcwd()
files_dir

'/home/jovyan/work'

In [18]:
dfs = pd.DataFrame()

for file in files:
    df = df_per_one_file(file, pick_headers)
    if not df.empty:
        print('The file ' + file + ' has been processed succesfully.')
    else:
        print('The file ' + file + ' has not been processed.')

    dfs = pd.concat([dfs, df], ignore_index=True)

The file idr0047-study.txt has been process succesfully.
The file idr0047-study.txt has been processed succesfully.
The file idr0038-study.txt has been process succesfully.
The file idr0038-study.txt has been processed succesfully.
The file idr0146-study.txt has been process succesfully.
The file idr0146-study.txt has been processed succesfully.
The file idr0054-study.txt has been process succesfully.
The file idr0054-study.txt has been processed succesfully.
The file idr0149-study.txt has been process succesfully.
The file idr0149-study.txt has been processed succesfully.
The file idr0138-study.txt has been process succesfully.
The file idr0138-study.txt has been processed succesfully.
The file idr0130-study.txt has been process succesfully.
The file idr0130-study.txt has been processed succesfully.
The file idr0013-study.txt has been process succesfully.
The file idr0013-study.txt has been processed succesfully.
The file idr0134-study.txt has been process succesfully.
The file idr0134-study.txt has been processed succesfully.
The file idr0042-study.txt has been process succesfully.
The file idr0042-study.txt has been processed succesfully.
The file idr0119-study.txt has been process succesfully.
The file idr0119-study.txt has been processed succesfully.
The file idr0127-study.txt has been process succesfully.
The file idr0127-study.txt has been processed succesfully.
The file idr0067-study.txt has been process succesfully.
The file idr0067-study.txt has been processed succesfully.
The file idr0061-study.txt has been process succesfully.
The file idr0061-study.txt has been processed succesfully.
The file idr0033-study.txt has been process succesfully.
The file idr0033-study.txt has been processed succesfully.
The file idr0064-study.txt has been process succesfully.
The file idr0064-study.txt has been processed succesfully.
The file idr0070-study.txt has been process succesfully.
The file idr0070-study.txt has been processed succesfully.
The file idr0094-study.txt has been process succesfully.
The file idr0094-study.txt has been processed succesfully.
The file idr0096-study.txt has been process succesfully.
The file idr0096-study.txt has been processed succesfully.
The file idr0148-study.txt has been process succesfully.
The file idr0148-study.txt has been processed succesfully.
The file idr0107-study.txt has been process succesfully.
The file idr0107-study.txt has been processed succesfully.
The file idr0035-study.txt has been process succesfully.
The file idr0035-study.txt has been processed succesfully.
The file idr0118-study.txt has been process succesfully.
The file idr0118-study.txt has been processed succesfully.
The file idr0124-study.txt has been process succesfully.
The file idr0124-study.txt has been processed succesfully.
The file idr0099-study.txt has been process succesfully.
The file idr0099-study.txt has been processed succesfully.
The file idr0056-study.txt has been process succesfully.
The file idr0056-study.txt has been processed succesfully.
The file idr0028-study.txt has been process succesfully.
The file idr0028-study.txt has been processed succesfully.
The file idr0073-study.txt has been process succesfully.
The file idr0073-study.txt has been processed succesfully.
The file idr0001-study.txt has been process succesfully.
The file idr0001-study.txt has been processed succesfully.
The file idr0068-study.txt has been process succesfully.
The file idr0068-study.txt has been processed succesfully.
The file idr0108-study.txt has been process succesfully.
The file idr0108-study.txt has been processed succesfully.
The file idr0133-study.txt has been process succesfully.
The file idr0133-study.txt has been processed succesfully.
The file idr0090-study.txt has been process succesfully.
The file idr0090-study.txt has been processed succesfully.
The file idr0113-study.txt has been process succesfully.
The file idr0113-study.txt has been processed succesfully.
The file idr0120-study.txt has been process succesfully.
The file idr0120-study.txt has been processed succesfully.
The file idr0077-study.txt has been process succesfully.
The file idr0077-study.txt has been processed succesfully.
The file idr0111-study.txt has been process succesfully.
The file idr0111-study.txt has been processed succesfully.
The file idr0114-study.txt has been process succesfully.
The file idr0114-study.txt has been processed succesfully.
The file idr0026-study.txt has been process succesfully.
The file idr0026-study.txt has been processed succesfully.
The file idr0071-study.txt has been process succesfully.
The file idr0071-study.txt has been processed succesfully.
The file idr0097-study.txt has been process succesfully.
The file idr0097-study.txt has been processed succesfully.
The file idr0091-study.txt has been process succesfully.
The file idr0091-study.txt has been processed succesfully.
The file idr0016-study.txt has been process succesfully.
The file idr0016-study.txt has been processed succesfully.
The file idr0110-study.txt has been process succesfully.
The file idr0110-study.txt has been processed succesfully.
The file idr0019-study.txt has been process succesfully.
The file idr0019-study.txt has been processed succesfully.
The file idr0069-study.txt has been process succesfully.
The file idr0069-study.txt has been processed succesfully.
The file idr0076-study.txt has been process succesfully.
The file idr0076-study.txt has been processed succesfully.
The file idr0043-study.txt has been process succesfully.
The file idr0043-study.txt has been processed succesfully.
The file idr0052-study.txt has been process succesfully.
The file idr0052-study.txt has been processed succesfully.
The file idr0154-study.txt has been process succesfully.
The file idr0154-study.txt has been processed succesfully.
The file idr0080-study.txt has been process succesfully.
The file idr0080-study.txt has been processed succesfully.
The file idr0128-study.txt has been process succesfully.
The file idr0128-study.txt has been processed succesfully.
The file idr0021-study.txt has been process succesfully.
The file idr0021-study.txt has been processed succesfully.
The file idr0086-study.txt has been process succesfully.
The file idr0086-study.txt has been processed succesfully.
The file idr0101-study.txt has been process succesfully.
The file idr0101-study.txt has been processed succesfully.
The file idr0084-study.txt has been process succesfully.
The file idr0084-study.txt has been processed succesfully.
The file idr0150-study.txt has been process succesfully.
The file idr0150-study.txt has been processed succesfully.
The file idr0095-study.txt has been process succesfully.
The file idr0095-study.txt has been processed succesfully.
The file idr0040-study.txt has been process succesfully.
The file idr0040-study.txt has been processed succesfully.
The file idr0051-study.txt has been process succesfully.
The file idr0051-study.txt has been processed succesfully.
The file idr0010-study.txt has been process succesfully.
The file idr0010-study.txt has been processed succesfully.
The file idr0032-study.txt has been process succesfully.
The file idr0032-study.txt has been processed succesfully.
The file idr0002-study.txt has been process succesfully.
The file idr0002-study.txt has been processed succesfully.
The file idr0092-study.txt has been process succesfully.
The file idr0092-study.txt has been processed succesfully.
The file idr0129-study.txt has been process succesfully.
The file idr0129-study.txt has been processed succesfully.
The file idr0083-study.txt has been process succesfully.
The file idr0083-study.txt has been processed succesfully.
The file idr0017-study.txt has been process succesfully.
The file idr0017-study.txt has been processed succesfully.
The file idr0098-study.txt has been process succesfully.
The file idr0098-study.txt has been processed succesfully.
The file idr0036-study.txt has been process succesfully.
The file idr0036-study.txt has been processed succesfully.
The file idr0037-study.txt has been process succesfully.
The file idr0037-study.txt has been processed succesfully.
The file idr0145-study.txt has been process succesfully.
The file idr0145-study.txt has been processed succesfully.
The file idr0004-study.txt has been process succesfully.
The file idr0004-study.txt has been processed succesfully.
The file idr0135-study.txt has been process succesfully.
The file idr0135-study.txt has been processed succesfully.
The file idr0143-study.txt has been process succesfully.
The file idr0143-study.txt has been processed succesfully.
The file idr0116-study.txt has been process succesfully.
The file idr0116-study.txt has been processed succesfully.
The file idr0088-study.txt has been process succesfully.
The file idr0088-study.txt has been processed succesfully.
The file idr0007-study.txt has been process succesfully.
The file idr0007-study.txt has been processed succesfully.
The file idr0078-study.txt has been process succesfully.
The file idr0078-study.txt has been processed succesfully.
The file idr0103-study.txt has been process succesfully.
The file idr0103-study.txt has been processed succesfully.
The file idr0063-study.txt has been process succesfully.
The file idr0063-study.txt has been processed succesfully.
The file idr0020-study.txt has been process succesfully.
The file idr0020-study.txt has been processed succesfully.
The file idr0140-study.txt has been process succesfully.
The file idr0140-study.txt has been processed succesfully.
The file idr0079-study.txt has been process succesfully.
The file idr0079-study.txt has been processed succesfully.
The file idr0123-study.txt has been process succesfully.
The file idr0123-study.txt has been processed succesfully.
The file idr0109-study.txt has been process succesfully.
The file idr0109-study.txt has been processed succesfully.
The file idr0147-study.txt has been process succesfully.
The file idr0147-study.txt has been processed succesfully.
The file idr0003-study.txt has been process succesfully.
The file idr0003-study.txt has been processed succesfully.
The file idr0112-study.txt has been process succesfully.
The file idr0112-study.txt has been processed succesfully.
The file idr0157-study.txt has been process succesfully.
The file idr0157-study.txt has been processed succesfully.
The file idr0115-study.txt has been process succesfully.
The file idr0115-study.txt has been processed succesfully.
The file idr0048-study.txt has been process succesfully.
The file idr0048-study.txt has been processed succesfully.
The file idr0100-study.txt has been process succesfully.
The file idr0100-study.txt has been processed succesfully.
The file idr0066-study.txt has been process succesfully.
The file idr0066-study.txt has been processed succesfully.
The file idr0012-study.txt has been process succesfully.
The file idr0012-study.txt has been processed succesfully.
The file idr0085-study.txt has been process succesfully.
The file idr0085-study.txt has been processed succesfully.
The file idr0045-study.txt has been process succesfully.
The file idr0045-study.txt has been processed succesfully.
The file idr0141-study.txt has been process succesfully.
The file idr0141-study.txt has been processed succesfully.
The file idr0087-study.txt has been process succesfully.
The file idr0087-study.txt has been processed succesfully.
The file idr0081-study.txt has been process succesfully.
The file idr0081-study.txt has been processed succesfully.
The file idr0089-study.txt has been process succesfully.
The file idr0089-study.txt has been processed succesfully.
The file idr0117-study.txt has been process succesfully.
The file idr0117-study.txt has been processed succesfully.
The file idr0053-study.txt has been process succesfully.
The file idr0053-study.txt has been processed succesfully.
The file idr0072-study.txt has been process succesfully.
The file idr0072-study.txt has been processed succesfully.
The file idr0062-study.txt has been process succesfully.
The file idr0062-study.txt has been processed succesfully.
The file idr0041-study.txt has been process succesfully.
The file idr0041-study.txt has been processed succesfully.
The file idr0050-study.txt has been process succesfully.
The file idr0050-study.txt has been processed succesfully.
The file idr0075-study.txt has been process succesfully.
The file idr0075-study.txt has been processed succesfully.
The file idr0082-study.txt has been process succesfully.
The file idr0082-study.txt has been processed succesfully.
The file idr0034-study.txt has been process succesfully.
The file idr0034-study.txt has been processed succesfully.
The file idr0025-study.txt has been process succesfully.
The file idr0025-study.txt has been processed succesfully.
The file idr0158-study.txt has been process succesfully.
The file idr0158-study.txt has been processed succesfully.
The file idr0030-study.txt has been process succesfully.
The file idr0030-study.txt has been processed succesfully.
The file idr0005-study.txt has been process succesfully.
The file idr0005-study.txt has been processed succesfully.
The file idr0018-study.txt has been process succesfully.
The file idr0018-study.txt has been processed succesfully.
The file idr0006-study.txt has been process succesfully.
The file idr0006-study.txt has been processed succesfully.
The file idr0008-study.txt has been process succesfully.
The file idr0008-study.txt has been processed succesfully.
The file idr0023-study.txt has been process succesfully.
The file idr0023-study.txt has been processed succesfully.
The file idr0009-study.txt has been process succesfully.
The file idr0009-study.txt has been processed succesfully.
The file idr0139-study.txt has been process succesfully.
The file idr0139-study.txt has been processed succesfully.
The file idr0144-study.txt has been process succesfully.
The file idr0144-study.txt has been processed succesfully.
The file idr0065-study.txt has been process succesfully.
The file idr0065-study.txt has been processed succesfully.
The file idr0011-study.txt has been process succesfully.
The file idr0011-study.txt has been processed succesfully.
The file idr0106-study.txt has been process succesfully.
The file idr0106-study.txt has been processed succesfully.
The file idr0015-study.txt has been process succesfully.
The file idr0015-study.txt has been processed succesfully.
The file idr0022-study.txt has been process succesfully.
The file idr0022-study.txt has been processed succesfully.
The file idr0155-study.txt has been process succesfully.
The file idr0155-study.txt has been processed succesfully.
The file idr0044-study.txt has been process succesfully.
The file idr0044-study.txt has been processed succesfully.
The file idr0093-study.txt has been process succesfully.
The file idr0093-study.txt has been processed succesfully.
The file idr0137-study.txt has been process succesfully.
The file idr0137-study.txt has been processed succesfully.
The file idr0027-study.txt has been process succesfully.
The file idr0027-study.txt has been processed succesfully.

In [19]:
dfs

,Comment[IDR_Study_Accession],Study_Title,Study_Type,Study_Type_Term_Source_REF,Study_Type_Term_Accession,Study_Description,Study_Organism,Study_Public_Release_Date,Study_PubMed_ID,Study_Publication_Title,...,Study_DOI,Study_Person_Last_Name,Study_Person_First_Name,Study_Person_Email,Study_Person_Roles,Experiment_Description,Protocol_Name,Protocol_Type_Term_Source_REF,Protocol_Type_Term_Accession,Protocol_Description
0,idr0047,A microscopy data set of discrete spatial and ...,fluorescence in situ hybridization,NCIT,NCIT_C17563,We report a comprehensive single cell dataset ...,Saccharomyces cerevisiae,2019-01-16,31209217,Multiplex RNA single molecule FISH of inducibl...,...,https://doi.org/10.1038/s41597-019-0106-6,Neuert,Gregor,gregor.neuert@vanderbilt.edu,submitter,We performed single molecule in-situ hybridiza...,growth protocol treatment protocol image acqui...,EFO EFO,EFO_0003789 EFO_0003969,"CSM, 30C 0.2M NaCl, step TRANS: brightfield of..."
1,idr0038,Ex vivo live cell tracking in kidney organoids...,time-lapse imaging,OMIT,OMIT_0027490,We have adapted the mouse kidney rudiment assa...,Mus musculus,2017-12-04,30048451,Ex vivo live cell tracking in kidney organoids...,...,https://doi.org/10.1371/journal.pone.0199918,Held Levy,Marie Raphael,m.held@liverpool.ac.uk Rapha@liverpool.ac.uk,submitter Principal Investigator,We have adapted the mouse kidney rudiment assa...,TIME SERIES GROWTH PROTOCOL TIME SERIES IMAGE ...,EFO,EFO_0003789,"""Kidneys were isolated from E13.5 embryos afte..."
2,idr0146,Time lapse imaging of mesoderm and early cardi...,time-lapse imaging ...,OMIT,OMIT_0027490,Using four-dimensional whole-embryo light shee...,Mus musculus,2023-02-06,36736300,Graded mesoderm assembly governs cell fate and...,...,https://doi.org/10.1016/j.cell.2023.01.001 ...,Bruneau Dominguez,Benoit Martin,benoit.bruneau@gladstone.ucsf.edu martin.domin...,submitter submitter ...,Light-sheet imaging of post-implantation mouse...,culture protocol embedding protocol Zeiss Z.1 ...,EFO EFO,EFO_0003789 EFO_0003969 ...,see attached DominguezMH Embryo Culture.pdf se...
3,idr0054,Imaging Mass Cytometry of human tonsil sections,image cytometry,OMIT,OMIT_0019157,We analysed the in situ localisation of immune...,Homo sapiens,2019-03-19,31072818,Human lymphoid organ cDC2 and macrophages play...,...,https://doi.org/10.1084/jem.20181994,Segura,Elodie,elodie.segura@curie.fr,submitter,Imaging mass cytometry of tonsil sections,growth protocol treatment protocol image aquis...,EFO EFO,EFO_0003789 EFO_0003969,Human tonsils were fixed in 4% paraformaldehyd...
4,idr0149,Cohesin-mediated DNA loop extrusion resolves s...,protein localization ...,EFO,GO_0008104,Genetic information is stored in linear DNA mo...,Homo sapiens,2023-08-17,37357575,Cohesin-mediated DNA loop extrusion resolves s...,...,https://doi.org/10.15252/embj.2023113475 ...,Batty Gerlich,Paul Daniel,paul.batty@imba.oeaw.ac.at daniel.gerlich@imba...,submitter corresponding author ...,Immunofluorescence of nuclear Sororin fluoresc...,growth protocol treatment protocol image acqu...,EFO EFO,EFO_0003789 EFO_0003969 ...,To assess nuclear Sororin fluorescence in Soro...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,idr0155,A new method for reliably detecting single flu...,protein localization,EFO,GO_0008104,Super-resolution and single-molecule microscop...,Homo sapiens,2024-03-05,,RASP: Optimal single puncta detection in compl...,...,,Fu Lee,Bin Steven,bf341@cam.ac.uk sl591@cam.ac.uk,First Author Principal Investigator,We took 5400 field of views from three Parkins...,treatment protocol image acquisition and featu...,EFO,EFO_0003969,Tissue sections were incubated with primary an...
126,idr0044,In Toto Imaging and Reconstruction of Post-Imp...,time-lapse imaging,OMIT,OMIT_0027490,The mouse embryo has long been central to the ...,Mus musculus,2018-11-29,30318151,In Toto Imaging and Reconstruction of Post-Imp...,...,https://doi.org/10.1016/j.cell.2018.09.031,Keller Kate Leo,Philipp McDole Guignard,kellerp@janelia.hhmi.org mcdolek@janelia.hhmi....,submitter submitter submitter,Light-sheet imaging of post-implantation mouse...,See attached methods N/A See attached methods ...,EFO N/A,EFO_0001746 N/A,See attached methods N/A See attached methods ...
127,idr0093,High content genome-wide siRNA screen to inves...,high content screen,EFO,EFO_0007550,Coordination of RNA abundance and transcriptio...,Homo sapiens,2021-03-17,,High content genome-wide siRNA screen to inves...,...,,MÃ¼ller Berry,Micha Scott,micha.mueller@mls.uzh.ch scott.berry@uzh.ch ...,submitter ...,NaN,growth protocol treatment protocol HCS library...,EFO EFO EFO EFO EFO,EFO_0003789 EFO_0003969 EFO_0007571 EFO_000757...,5nl of 5Î¼M siRNAs from the Ambion Silencer Se...
128,idr0137,Reference BioImaging dataset to assess the phe...,phenotype,EFO,EFO_0000651,A reference dataset containing macroscopic and...,Riccia glauca Riccia sorocarpa Riccia warnstor...,2023-01-17,,Data integration in biodiversity - A principal...,...,,Peters,Kristian,kristian.peters@idiv.de ...,submitter,"Samples of R. glauca, R. sorocarpa, R. warnsto...",growth protocol treatment protocol image acqui...,EFO EFO,EFO_0003789 EFO_0003969 ...,
129,idr0027,High resolution imaging reveals heterogeneity ...,time-lapse imaging,OMIT,OMIT_0027490,We established a work flow for measuring the d...,Saccharomyces cerevisiae,2016-11-01,27609610,High resolution imaging reveals heterogeneity ...,...,https://doi.org/10.1186/s12860-016-0111-y,Dickerson Owen-Hughes,David Tom,D.Dickerson@dundee.ac.uk t.a.owenhughes@dundee...,submitter principal investigator,To monitor the organisation of chromatin in li...,growth protocol image aquistion and feature ex...,EFO,EFO_0003789,The S. cerevisiae strains in this study are su...

In [20]:
dfs['Description_combined'] = dfs['Study_Description'].astype(str) + ' .' + dfs['Experiment_Description'].astype(str) + ' .' + dfs['Protocol_Description'].astype(str) + '.'

In [21]:
dfs

,Comment[IDR_Study_Accession],Study_Title,Study_Type,Study_Type_Term_Source_REF,Study_Type_Term_Accession,Study_Description,Study_Organism,Study_Public_Release_Date,Study_PubMed_ID,Study_Publication_Title,...,Study_Person_Last_Name,Study_Person_First_Name,Study_Person_Email,Study_Person_Roles,Experiment_Description,Protocol_Name,Protocol_Type_Term_Source_REF,Protocol_Type_Term_Accession,Protocol_Description,Description_combined
0,idr0047,A microscopy data set of discrete spatial and ...,fluorescence in situ hybridization,NCIT,NCIT_C17563,We report a comprehensive single cell dataset ...,Saccharomyces cerevisiae,2019-01-16,31209217,Multiplex RNA single molecule FISH of inducibl...,...,Neuert,Gregor,gregor.neuert@vanderbilt.edu,submitter,We performed single molecule in-situ hybridiza...,growth protocol treatment protocol image acqui...,EFO EFO,EFO_0003789 EFO_0003969,"CSM, 30C 0.2M NaCl, step TRANS: brightfield of...",We report a comprehensive single cell dataset ...
1,idr0038,Ex vivo live cell tracking in kidney organoids...,time-lapse imaging,OMIT,OMIT_0027490,We have adapted the mouse kidney rudiment assa...,Mus musculus,2017-12-04,30048451,Ex vivo live cell tracking in kidney organoids...,...,Held Levy,Marie Raphael,m.held@liverpool.ac.uk Rapha@liverpool.ac.uk,submitter Principal Investigator,We have adapted the mouse kidney rudiment assa...,TIME SERIES GROWTH PROTOCOL TIME SERIES IMAGE ...,EFO,EFO_0003789,"""Kidneys were isolated from E13.5 embryos afte...",We have adapted the mouse kidney rudiment assa...
2,idr0146,Time lapse imaging of mesoderm and early cardi...,time-lapse imaging ...,OMIT,OMIT_0027490,Using four-dimensional whole-embryo light shee...,Mus musculus,2023-02-06,36736300,Graded mesoderm assembly governs cell fate and...,...,Bruneau Dominguez,Benoit Martin,benoit.bruneau@gladstone.ucsf.edu martin.domin...,submitter submitter ...,Light-sheet imaging of post-implantation mouse...,culture protocol embedding protocol Zeiss Z.1 ...,EFO EFO,EFO_0003789 EFO_0003969 ...,see attached DominguezMH Embryo Culture.pdf se...,Using four-dimensional whole-embryo light shee...
3,idr0054,Imaging Mass Cytometry of human tonsil sections,image cytometry,OMIT,OMIT_0019157,We analysed the in situ localisation of immune...,Homo sapiens,2019-03-19,31072818,Human lymphoid organ cDC2 and macrophages play...,...,Segura,Elodie,elodie.segura@curie.fr,submitter,Imaging mass cytometry of tonsil sections,growth protocol treatment protocol image aquis...,EFO EFO,EFO_0003789 EFO_0003969,Human tonsils were fixed in 4% paraformaldehyd...,We analysed the in situ localisation of immune...
4,idr0149,Cohesin-mediated DNA loop extrusion resolves s...,protein localization ...,EFO,GO_0008104,Genetic information is stored in linear DNA mo...,Homo sapiens,2023-08-17,37357575,Cohesin-mediated DNA loop extrusion resolves s...,...,Batty Gerlich,Paul Daniel,paul.batty@imba.oeaw.ac.at daniel.gerlich@imba...,submitter corresponding author ...,Immunofluorescence of nuclear Sororin fluoresc...,growth protocol treatment protocol image acqu...,EFO EFO,EFO_0003789 EFO_0003969 ...,To assess nuclear Sororin fluorescence in Soro...,Genetic information is stored in linear DNA mo...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,idr0155,A new method for reliably detecting single flu...,protein localization,EFO,GO_0008104,Super-resolution and single-molecule microscop...,Homo sapiens,2024-03-05,,RASP: Optimal single puncta detection in compl...,...,Fu Lee,Bin Steven,bf341@cam.ac.uk sl591@cam.ac.uk,First Author Principal Investigator,We took 5400 field of views from three Parkins...,treatment protocol image acquisition and featu...,EFO,EFO_0003969,Tissue sections were incubated with primary an...,Super-resolution and single-molecule microscop...
126,idr0044,In Toto Imaging and Reconstruction of Post-Imp...,time-lapse imaging,OMIT,OMIT_0027490,The mouse embryo has long been central to the ...,Mus musculus,2018-11-29,30318151,In Toto Imaging and Reconstruction of Post-Imp...,...,Keller Kate Leo,Philipp McDole Guignard,kellerp@janelia.hhmi.org mcdolek@janelia.hhmi....,submitter submitter submitter,Light-sheet imaging of post-implantation mouse...,See attached methods N/A See attached methods ...,EFO N/A,EFO_0001746 N/A,See attached methods N/A See attached methods ...,The mouse embryo has long been central to the ...
127,idr0093,High content genome-wide siRNA screen to inves...,high content screen,EFO,EFO_0007550,Coordination of RNA abundance and transcriptio...,Homo sapiens,2021-03-17,,High content genome-wide siRNA screen to inves...,...,MÃ¼ller Berry,Micha Scott,micha.mueller@mls.uzh.ch scott.berry@uzh.ch ...,submitter ...,NaN,growth protocol treatment protocol HCS library...,EFO EFO EFO EFO EFO,EFO_0003789 EFO_0003969 EFO_0007571 EFO_000757...,5nl of 5Î¼M siRNAs from the Ambion Silencer Se...,Coordination of RNA abundance and transcriptio...
128,idr0137,Reference BioImaging dataset to assess the phe...,phenotype,EFO,EFO_0000651,A reference dataset containing macroscopic and...,Riccia glauca Riccia sorocarpa Riccia warnstor...,2023-01-17,,Data integration in biodiversity - A principal...,...,Peters,Kristian,kristian.peters@idiv.de ...,submitter,"Samples of R. glauca, R. sorocarpa, R. warnsto...",growth protocol treatment protocol image acqui...,EFO EFO,EFO_0003789 EFO_0003969 ...,,A reference dataset containing macroscopic and...
129,idr0027,High resolution imaging reveals heterogeneity ...,time-lapse imaging,OMIT,OMIT_0027490,We established a work flow for measuring the d...,Saccharomyces cerevisiae,2016-11-01,27609610,High resolution imaging reveals heterogeneity ...,...,Dickerson Owen-Hughes,David Tom,D.Dickerson@dundee.ac.uk t.a.owenhughes@dundee...,submitter principal investigator,To monitor the organisation of chromatin in li...,growth protocol image aquistion and feature ex...,EFO,EFO_0003789,The S. cerevisiae strains in this study are su...,We established a work flow for measuring the d...

In [23]:
for row, i in dfs.iterrows():
    
    message = [
    {"role": "system", "content": i["Description_combined"]},
    {"role": "user", "content": "Can you tell me which specie was used in this study?"},
     ]

    outputs = pipe(message, max_new_tokens = 256)
    response = outputs[0]["generated_text"][-1]["content"]
    dfs.at[row, 'Only_descriptions_species'] = response
    print(f"Processed row {row} for species extraction.")

    if isinstance(i['Study_Organism'], str) and i['Study_Organism'].strip() != '':

        real_specie = i['Study_Organism'][0]

        if real_specie in response:
            print('The real species is in the response.')
            dfs.at[row, 'Real_Species_in_Response_descriptions'] = 'Yes'
        else:
            print('The real species is NOT in the response.')
            dfs.at[row, 'Real_Species_in_Response_descriptions'] = 'No'
    else:
        print('No real species to check in the response.')
        dfs.at[row, 'Real_Species_in_Response_descriptions'] = 'No species provided'

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 0 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 1 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 2 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 3 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 4 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 5 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 6 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 7 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 8 for species extraction.
The real species is in the response.

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 9 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 10 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 11 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 12 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 13 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 14 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 15 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 16 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 17 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 18 for species extraction.
No real species to check in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 19 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 20 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 21 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 22 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 23 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 24 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 25 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 26 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 27 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 28 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 29 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 30 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 31 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 32 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 33 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 34 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 35 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 36 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 37 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 38 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 39 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 40 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 41 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 42 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 43 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 44 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 45 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 46 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 47 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 48 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 49 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 50 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 51 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 52 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 53 for species extraction.
No real species to check in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 54 for species extraction.
No real species to check in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 55 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 56 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 57 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 58 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 59 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 60 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 61 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 62 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 63 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 64 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 65 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 66 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 67 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 68 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 69 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 70 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 71 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 72 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 73 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 74 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 75 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 76 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 77 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 78 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 79 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 80 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 81 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 82 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 83 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 84 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 85 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 86 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 87 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 88 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 89 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 90 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 91 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 92 for species extraction.
No real species to check in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 93 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 94 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 95 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 96 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 97 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 98 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 99 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 100 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 101 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 102 for species extraction.
No real species to check in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 103 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 104 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 105 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 106 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 107 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 108 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 109 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 110 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 111 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 112 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 113 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 114 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 115 for species extraction.
No real species to check in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 116 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 117 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 118 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 119 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 120 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 121 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 122 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 123 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 124 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 125 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 126 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 127 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 128 for species extraction.
The real species is in the response.
Processed row 129 for species extraction.
The real species is in the response.

In [24]:
dfs['Real_Species_in_Response_descriptions'].value_counts()

Real_Species_in_Response_descriptions
Yes                    79
No                     45
No species provided     6
Name: count, dtype: int64

##### All information provided

In [22]:
for row, i in dfs.iterrows():
    
    message = [
    {"role": "system", "content": i},
    {"role": "user", "content": "Can you give me 3 possible species that could be used in this study?"},
     ]

    outputs = pipe(message, max_new_tokens = 256)
    response = outputs[0]["generated_text"][-1]["content"]
    dfs.at[row, 'All_info_species'] = response
    print(f"Processed row {row} for species extraction.")

    if isinstance(i['Study_Organism'], str) and i['Study_Organism'].strip() != '':

        real_specie = i['Study_Organism'][0]
        if real_specie in response:
            print('The real species is in the response.')
            dfs.at[row, 'Real_Species_in_Response_all_info'] = 'Yes'
        else:
            print('The real species is NOT in the response.')
            dfs.at[row, 'Real_Species_in_Response_all_info'] = 'No'
    else:
        print('No real species to check in the response.')
        dfs.at[row, 'Real_Species_in_Response_all_info'] = 'No species provided'

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

KeyboardInterrupt:

##### All info minus spceies info

In [48]:
#test_wo_species = test.drop(columns= ['Study_Organism', 'Study_Organism_Term_Accession', 'Study_Organism_Term_Accession'])
test_wo_species = dfs.drop(columns= ['Study_Organism', 'Only_descriptions_species', 'Real_Species_in_Response_descriptions', 'Real_Species_in_Response_all_info', 'All_info_species'])


for row, i in test_wo_species.iterrows():
    
    message = [
    {"role": "system", "content": i},
    {"role": "user", "content": "Can you give me 3 possible species that could be used in this study?"},
     ]

    outputs = pipe(message, max_new_tokens = 256)
    response = outputs[0]["generated_text"][-1]["content"]
    test_wo_species.at[row, 'All_info_minus_species'] = response
    print(f"Processed row {row} for species extraction.")

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 0 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 1 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 2 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 3 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 4 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 5 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 6 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 7 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 8 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 9 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 10 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 11 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 12 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 13 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 14 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 15 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 16 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 17 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 18 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 19 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 20 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 21 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 22 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 23 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 24 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 25 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 26 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 27 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 28 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 29 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 30 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 31 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 32 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 33 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 34 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 35 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 36 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 37 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 38 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 39 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 40 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 41 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 42 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 43 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 44 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 45 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 46 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 47 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 48 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 49 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 50 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 51 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 52 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 53 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 54 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 55 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 56 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 57 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 58 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 59 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 60 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 61 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 62 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 63 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 64 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 65 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 66 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 67 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 68 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 69 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 70 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 71 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 72 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 73 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 74 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 75 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 76 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 77 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 78 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 79 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 80 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 81 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 82 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 83 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 84 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 85 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 86 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 87 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 88 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 89 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 90 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 91 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 92 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 93 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 94 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 95 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 96 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 97 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 98 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 99 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 100 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 101 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 102 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 103 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 104 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 105 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 106 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 107 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 108 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 109 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 110 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 111 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 112 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 113 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 114 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 115 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 116 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 117 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 118 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 119 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 120 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 121 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 122 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 123 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 124 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 125 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 126 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 127 for species extraction.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 128 for species extraction.
Processed row 129 for species extraction.

In [50]:
dfs.columns

Index(['Comment[IDR_Study_Accession]', 'Study_Title', 'Study_Type',
       'Study_Type_Term_Source_REF', 'Study_Type_Term_Accession',
       'Study_Description', 'Study_Organism', 'Study_Public_Release_Date',
       'Study_PubMed_ID', 'Study_Publication_Title', 'Study_Author_List',
       'Study_DOI', 'Study_Person_Last_Name', 'Study_Person_First_Name',
       'Study_Person_Email', 'Study_Person_Roles', 'Experiment_Description',
       'Protocol_Name', 'Protocol_Type_Term_Source_REF',
       'Protocol_Type_Term_Accession', 'Protocol_Description',
       'Description_combined', 'Only_descriptions_species',
       'Real_Species_in_Response_descriptions', 'All_info_species',
       'Real_Species_in_Response_all_info'],
      dtype='object')

In [51]:
type(dfs)

pandas.core.frame.DataFrame

In [58]:
dfs.to_csv('IDR_Llama_3_2_metadata_test_20250729.csv', index=False)

#### Study type

In [24]:
raw_experiment_types = dfs['Study_Type'].to_list()
raw_experiment_types

['fluorescence in situ hybridization    ',
 'time-lapse imaging   ',
 'time-lapse imaging                                ',
 'image cytometry    ',
 'protein localization                                ',
 'seqFISH                                ',
 'high content screen infection                  ',
 'high content screen                                                                                                                                                                                                                                              ',
 'histology                                ',
 'histology     ',
 'high content screen                               ',
 'time-lapse imaging   ',
 'time-lapse imaging                                ',
 'high content screen               ',
 'high content screen                                  ',
 'high content screen        ',
 'protein localization in-situ hybridization assay    ',
 'high content screen of cells treated with a compound library infection      ',
 'histology scanned image            ',
 'electron microscopy volume map                                ',
 'protein localization  ',
 'high content screen     ',
 'time-lapse imaging                   ',
 'morphogenesis     ',
 'time-lapse imaging                     ',
 'high content screen      ',
 'high content screen                                                                                                                                          ',
 'histology         ',
 'high content screen                                                                                                                                                        ',
 'time-lapse imaging  ',
 'time-lapse imaging   ',
 'high content screen                                ',
 'high content screen',
 'time-lapse imaging ',
 'high content screen                                ',
 'time-lapse imaging',
 'time-lapse imaging         ',
 'protein localization in-situ hybridization assay                     ',
 'time-lapse imaging           ',
 'in situ sequencing',
 'in situ sequencing',
 'time-lapse imaging                     ',
 'high content screen    ',
 'X-chromosome inactivation   ',
 'high content analysis of cells                                                                                   ',
 'high content screen                                ',
 'image cytometry                                 ',
 'protein localization   ',
 'microscopy assay   ',
 'histology RNAscope   ',
 'high content screen',
 'high content screen infection                  ',
 'protein localization         ',
 'micrograph   ',
 'DNA sequencing                                      ',
 'fluorescence in situ hybridization',
 'multiplexed immunofluorescence   ',
 'metabolic network measurement',
 'time-lapse imaging ',
 'time-lapse imaging   ',
 'high content screen                ',
 'in-situ hybridization assay          ',
 'high content screen          ',
 'compound library screen           ',
 'high content screen infection                  ',
 'infection electron microscopy volume map                  ',
 'high content screen                                          ',
 'histology                    ',
 'high content screen               ',
 'high content screen      ',
 'high content screen    ',
 'high content screen           ',
 'histology                   ',
 'high content screen                                ',
 'electron microscopy volume map ',
 'high content screen     ',
 'high content screen                                ',
 'high content screen ',
 'process of establishing viral infection',
 'time-lapse imaging',
 'high content screen               ',
 'high content screen    ',
 'microscopy assay     ',
 'fluorescence in situ hybridization          ',
 'time-lapse imaging                        ',
 'machine learning                                ',
 'high content screen                           ',
 'high content screen                            ',
 'phenotype                               ',
 'time-lapse imaging                           ',
 'microscopy assay                                ',
 'myelination',
 'imaging method',
 'high content screen                                                       ',
 'microscopy assay   ',
 'spindle assembly',
 'electron microscopy volume map                               ',
 'time-lapse imaging                  ',
 'high content screen infection                  ',
 'response to cold                              ',
 'in-situ hybridization assay                                ',
 'electron microscopy volume map   ',
 'high content screen                     ',
 'image segmentation                                                           ',
 'protein localization',
 'immunocytochemistry                               ',
 'imaging method   ',
 'histology       ',
 'high content screen      ',
 'high content screen                 ',
 'multiplexed immunofluorescence   ',
 'high content screen                             ',
 'high content screen               ',
 'histology                                                       ',
 'high content screen                ',
 'high content screen                                                   ',
 'protein localization            ',
 'high content screen                ',
 'high content screen           ',
 'histology      ',
 'time-lapse imaging   ',
 'high content screen     ',
 'imaging method                                ',
 'high content screen    ',
 'high content screen    ',
 'protein localization   ',
 'time-lapse imaging   ',
 'high content screen                  ',
 'phenotype                               ',
 'time-lapse imaging   ']

In [25]:
# Make a list with all types of experiments
# This list will be used to create a list of all types of experiments, removing duplicates and cleaning the data.
# ------------------------------------------------------------
list_experiment_types_clean = []
for element in raw_experiment_types:
    element_clean = element.strip().replace('\n', '')
    list_experiment_types_clean.append(element_clean)

In [27]:
experiment_types = list(set(list_experiment_types_clean))
experiment_types.sort()
len(experiment_types)

34

In [28]:
experiment_types

['DNA sequencing',
 'X-chromosome inactivation',
 'compound library screen',
 'electron microscopy volume map',
 'fluorescence in situ hybridization',
 'high content analysis of cells',
 'high content screen',
 'high content screen infection',
 'high content screen of cells treated with a compound library infection',
 'histology',
 'histology RNAscope',
 'histology scanned image',
 'image cytometry',
 'image segmentation',
 'imaging method',
 'immunocytochemistry',
 'in situ sequencing',
 'in-situ hybridization assay',
 'infection electron microscopy volume map',
 'machine learning',
 'metabolic network measurement',
 'micrograph',
 'microscopy assay',
 'morphogenesis',
 'multiplexed immunofluorescence',
 'myelination',
 'phenotype',
 'process of establishing viral infection',
 'protein localization',
 'protein localization in-situ hybridization assay',
 'response to cold',
 'seqFISH',
 'spindle assembly',
 'time-lapse imaging']

In [29]:
for row, i in dfs.iterrows():
    
    message = [
    {"role": "system", "content": i['Description_combined']},
    {"role": "user", "content": "Choose the experiment type for this study from the following list: " + ', '.join(experiment_types) + ". If you don't know, just say 'I don't know'."},
     ]

    outputs = pipe(message, max_new_tokens = 256)
    response = outputs[0]["generated_text"][-1]["content"]
    dfs.at[row, 'Only_descriptions_study_type'] = response
    print(f"Processed row {row} for study_type extraction.")

    if isinstance(i['Study_Type'], str) and i['Study_Type'].strip() != '':

        real_specie = i['Study_Type'][0]
        if real_specie in response:
            print('The real study type is in the response.')
            dfs.at[row, 'Study_type_only_descriptions'] = 'Yes'
        else:
            print('The real study type is NOT in the response.')
            dfs.at[row, 'Study_type_only_descriptions'] = 'No'
    else:
        print('No study type to check in the response.')
        dfs.at[row, 'Study_type_only_descriptions'] = 'No study type provided'

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 0 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 1 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 2 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 3 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 4 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 5 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 6 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 7 for study_type extraction.
The real study type is in the response.

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 8 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 9 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 10 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 11 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 12 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 13 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 14 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 15 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 16 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 17 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 18 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 19 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 20 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 21 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 22 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 23 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 24 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 25 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 26 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 27 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 28 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 29 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 30 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 31 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 32 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 33 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 34 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 35 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 36 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 37 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 38 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 39 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 40 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 41 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 42 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 43 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 44 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 45 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 46 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 47 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 48 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 49 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 50 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 51 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 52 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 53 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 54 for study_type extraction.
The real study type is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 55 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 56 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 57 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 58 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 59 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 60 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 61 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 62 for study_type extraction.
The real study type is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 63 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 64 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 65 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 66 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 67 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 68 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 69 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 70 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 71 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 72 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 73 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 74 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 75 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 76 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 77 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 78 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 79 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 80 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 81 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 82 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 83 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 84 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 85 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 86 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 87 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 88 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 89 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 90 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 91 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 92 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 93 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 94 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 95 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 96 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 97 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 98 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 99 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 100 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 101 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 102 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 103 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 104 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 105 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 106 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 107 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 108 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 109 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 110 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 111 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 112 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 113 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 114 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 115 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 116 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 117 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 118 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 119 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 120 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 121 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 122 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 123 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 124 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 125 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 126 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 127 for study_type extraction.
The real study type is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 128 for study_type extraction.
The real study type is in the response.
Processed row 129 for study_type extraction.
The real study type is in the response.

In [30]:
dfs.to_csv('IDR_Llama_3_2_metadata_test_20250805_study_type.csv', index=False)

### Clasical pathway

In [23]:
# Load the spaCy model
## This model have the tags on it. One of them is 'ORG' so I choose it to extract the species.

nlp = spacy.load("en_ner_bionlp13cg_md")

/opt/conda/lib/python3.11/site-packages/spacy/language.py:2195: FutureWarning: Possible set union at position 6328
  deserializers["tokenizer"] = lambda p: self.tokenizer.from_disk(  # type: ignore[union-attr]

In [24]:
# Function to extract species from the combined descriptions
# This function takes a text input, processes it with the spaCy model, and extracts named entities related to species.
# It returns a dictionary with the entity labels as keys and the corresponding entity texts as values.
# The function uses the spaCy model to identify named entities in the text and groups them by their entity labels.
# The output is a dictionary where the keys are the entity labels (e.g., 'ORG' for organisms) and the values are lists of entity texts that correspond to those labels.
# ------------------------------------------------------------  

def extract_species(text):
    doc= nlp(text)
    entities = [(ent.text, ent.label_) for ent in doc.ents]

    dictionary_entities = {}
    for k,v in entities:
        if v not in dictionary_entities:
            dictionary_entities[v]=[]
        dictionary_entities[v].append(k)
    
    return dictionary_entities

In [25]:
# Extracting species from the combined descriptions
# This will create a new column in the pick_headers_df dataframe with the extracted species from the combined descriptions.
# The extracted species will be stored in a dictionary with the entity type as the key
# and the list of species as the value.
# ------------------------------------------------------------

for row, item in dfs.iterrows():
    my_text = item['Description_combined']
    dic_entities = extract_species(my_text)

    dfs.at[row, 'Entities_SpaCy'] = str(dic_entities)

In [26]:
# Creating a new column with the species extracted from the Entities_SpaCy column
# This column will be used to store the species extracted from the Entities_SpaCy column.
# It used ast to transform the string representation of the dictionary into a dictionary object.
# --------------------------------------------------------------

for row, item in dfs.iterrows():
    dataframe_row = dfs.loc[row, 'Entities_SpaCy']
    dictionary_entities = ast.literal_eval(dataframe_row)
    entities_keys = dictionary_entities.keys()

    if ('ORGANISM') in entities_keys:
        
        dfs.at[row, 'Species_SpaCy'] = dictionary_entities['ORGANISM'] if 'ORGANISM' in entities_keys else "Not found"
    else:
        dfs.at[row, 'Species_SpaCy'] = 'Not found'

In [27]:
dfs

,Comment[IDR_Study_Accession],Study_Title,Study_Type,Study_Type_Term_Source_REF,Study_Type_Term_Accession,Study_Description,Study_Organism,Study_Public_Release_Date,Study_PubMed_ID,Study_Publication_Title,...,Study_Person_Email,Study_Person_Roles,Experiment_Description,Protocol_Name,Protocol_Type_Term_Source_REF,Protocol_Type_Term_Accession,Protocol_Description,Description_combined,Entities_SpaCy,Species_SpaCy
0,idr0047,A microscopy data set of discrete spatial and ...,fluorescence in situ hybridization,NCIT,NCIT_C17563,We report a comprehensive single cell dataset ...,Saccharomyces cerevisiae,2019-01-16,31209217,Multiplex RNA single molecule FISH of inducibl...,...,gregor.neuert@vanderbilt.edu,submitter,We performed single molecule in-situ hybridiza...,growth protocol treatment protocol image acqui...,EFO EFO,EFO_0003789 EFO_0003969,"CSM, 30C 0.2M NaCl, step TRANS: brightfield of...",We report a comprehensive single cell dataset ...,"{'CELL': ['cell', 'cerevisiae', 'cells', 'cell...",[Excelitas]
1,idr0038,Ex vivo live cell tracking in kidney organoids...,time-lapse imaging,OMIT,OMIT_0027490,We have adapted the mouse kidney rudiment assa...,Mus musculus,2017-12-04,30048451,Ex vivo live cell tracking in kidney organoids...,...,m.held@liverpool.ac.uk Rapha@liverpool.ac.uk,submitter Principal Investigator,We have adapted the mouse kidney rudiment assa...,TIME SERIES GROWTH PROTOCOL TIME SERIES IMAGE ...,EFO,EFO_0003789,"""Kidneys were isolated from E13.5 embryos afte...",We have adapted the mouse kidney rudiment assa...,"{'ORGANISM': ['mouse kidney rudiment', 'E13.5 ...","[mouse kidney rudiment, E13.5 embryonic kidney..."
2,idr0146,Time lapse imaging of mesoderm and early cardi...,time-lapse imaging ...,OMIT,OMIT_0027490,Using four-dimensional whole-embryo light shee...,Mus musculus,2023-02-06,36736300,Graded mesoderm assembly governs cell fate and...,...,benoit.bruneau@gladstone.ucsf.edu martin.domin...,submitter submitter ...,Light-sheet imaging of post-implantation mouse...,culture protocol embedding protocol Zeiss Z.1 ...,EFO EFO,EFO_0003789 EFO_0003969 ...,see attached DominguezMH Embryo Culture.pdf se...,Using four-dimensional whole-embryo light shee...,"{'ORGANISM': ['murine cardiac', 'mouse', 'E6.5...","[murine cardiac, mouse, E6.5]"
3,idr0054,Imaging Mass Cytometry of human tonsil sections,image cytometry,OMIT,OMIT_0019157,We analysed the in situ localisation of immune...,Homo sapiens,2019-03-19,31072818,Human lymphoid organ cDC2 and macrophages play...,...,elodie.segura@curie.fr,submitter,Imaging mass cytometry of tonsil sections,growth protocol treatment protocol image aquis...,EFO EFO,EFO_0003789 EFO_0003969,Human tonsils were fixed in 4% paraformaldehyd...,We analysed the in situ localisation of immune...,"{'CELL': ['immune cell'], 'ORGANISM': ['human ...","[human tonsils, .Human tonsils, Bovine Serum A..."
4,idr0149,Cohesin-mediated DNA loop extrusion resolves s...,protein localization ...,EFO,GO_0008104,Genetic information is stored in linear DNA mo...,Homo sapiens,2023-08-17,37357575,Cohesin-mediated DNA loop extrusion resolves s...,...,paul.batty@imba.oeaw.ac.at daniel.gerlich@imba...,submitter corresponding author ...,Immunofluorescence of nuclear Sororin fluoresc...,growth protocol treatment protocol image acqu...,EFO EFO,EFO_0003789 EFO_0003969 ...,To assess nuclear Sororin fluorescence in Soro...,Genetic information is stored in linear DNA mo...,"{'CELLULAR_COMPONENT': ['DNA', 'DNA', 'nuclear...",[human]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,idr0155,A new method for reliably detecting single flu...,protein localization,EFO,GO_0008104,Super-resolution and single-molecule microscop...,Homo sapiens,2024-03-05,,RASP: Optimal single puncta detection in compl...,...,bf341@cam.ac.uk sl591@cam.ac.uk,First Author Principal Investigator,We took 5400 field of views from three Parkins...,treatment protocol image acquisition and featu...,EFO,EFO_0003969,Tissue sections were incubated with primary an...,Super-resolution and single-molecule microscop...,"{'CELL': ['cells', 'cell', 'cells', 'cellular'...","[human brain, patient]"
126,idr0044,In Toto Imaging and Reconstruction of Post-Imp...,time-lapse imaging,OMIT,OMIT_0027490,The mouse embryo has long been central to the ...,Mus musculus,2018-11-29,30318151,In Toto Imaging and Reconstruction of Post-Imp...,...,kellerp@janelia.hhmi.org mcdolek@janelia.hhmi....,submitter submitter submitter,Light-sheet imaging of post-implantation mouse...,See attached methods N/A See attached methods ...,EFO N/A,EFO_0001746 N/A,See attached methods N/A See attached methods ...,The mouse embryo has long been central to the ...,"{'ORGANISM': ['mouse embryo', 'mouse', 'mouse'...","[mouse embryo, mouse, mouse, mouse, E6.5]"
127,idr0093,High content genome-wide siRNA screen to inves...,high content screen,EFO,EFO_0007550,Coordination of RNA abundance and transcriptio...,Homo sapiens,2021-03-17,,High content genome-wide siRNA screen to inves...,...,micha.mueller@mls.uzh.ch scott.berry@uzh.ch ...,submitter ...,NaN,growth protocol treatment protocol HCS library...,EFO EFO EFO EFO EFO,EFO_0003789 EFO_0003969 EFO_0007571 EFO_000757...,5nl of 5Î¼M siRNAs from the Ambion Silencer Se...,Coordination of RNA abundance and transcriptio...,"{'CELL': ['cell', 'cell', 'cells', 'single-cel...",[human cells]
128,idr0137,Reference BioImaging dataset to assess the phe...,phenotype,EFO,EFO_0000651,A reference dataset containing macroscopic and...,Riccia glauca Riccia sorocarpa Riccia warnstor...,2023-01-17,,Data integration in biodiversity - A principal...,...,kristian.peters@idiv.de ...,submitter,"Samples of R. glauca, R. sorocarpa, R. warnsto...",growth protocol treatment protocol image acqui...,EFO EFO,EFO_0003789 EFO_0003969 ...,,A reference dataset containing macroscopic and...,"{'CANCER': ['glauca', 'specimens', 'CB3', 'CR3...","[Riccia glauca, TSV]"
129,idr0027,High resolution imaging reveals heterogeneity ...,time-lapse imaging,OMIT,OMIT_0027490,We established a work flow for measuring the d...,Saccharomyces cerevisiae,2016-11-01,27609610,High resolution imaging reveals heterogeneity ...,...,D.Dickerson@dundee.ac.uk t.a.owenhughes@dundee...,submitter principal investigator,To monitor the organisation of chromatin in li...,growth protocol image aquistion and feature ex...,EFO,EFO_0003789,The S. cerevisiae strains in this study are su...,We established a work flow for measuring the d...,"{'CELLULAR_COMPONENT': ['chromatin', 'chromati...",Not found

In [28]:
for i, item in dfs.iterrows():
    list_species_spacy = item['Species_SpaCy']
    list_species_scientific_name = []

    for x in list_species_spacy:
        values = x.split(' ')
        #print(values)
        for unique_value in values:
            #print(unique_value)
            
            url = f'https://www.ebi.ac.uk/ena/taxonomy/rest/any-name/{unique_value}'
            #print(url)

            response = requests.get(url)
        
            if response.status_code == 200:
                data = response.json()
                #print(data)
                if data:
                    scientific_name = data[0]['scientificName']
                    #print("found")

                    list_species_scientific_name.append(scientific_name)
                    print(f"Scientific name for {x}: {scientific_name}")
                else:
                    scientific_name = 'Not found'
                    print(f"Scientific name for {x}: {scientific_name}")

    dfs.at[i, 'Species_Scientific_Name_SciSpacy'] = str(list_species_scientific_name)

Scientific name for Excelitas: Not found
Scientific name for mouse kidney rudiment: Mus musculus
Scientific name for mouse kidney rudiment: Not found
Scientific name for mouse kidney rudiment: Not found
Scientific name for E13.5 embryonic kidneys: Not found
Scientific name for E13.5 embryonic kidneys: Not found
Scientific name for E13.5 embryonic kidneys: Not found
Scientific name for Wt1-GFP knock-in cells: Not found
Scientific name for Wt1-GFP knock-in cells: Not found
Scientific name for Wt1-GFP knock-in cells: Not found
Scientific name for mouse kidney rudiment: Mus musculus
Scientific name for mouse kidney rudiment: Not found
Scientific name for mouse kidney rudiment: Not found
Scientific name for mouse kidney cells: Mus musculus
Scientific name for mouse kidney cells: Not found
Scientific name for mouse kidney cells: Not found
Scientific name for mice: Mus sp.
Scientific name for E13.5 embryos: Not found
Scientific name for E13.5 embryos: Not found
Scientific name for mice: Mus sp.
Scientific name for mice: Mus sp.
Scientific name for mice: Mus sp.
Scientific name for Margate: Not found
Scientific name for murine cardiac: Not found
Scientific name for murine cardiac: Not found
Scientific name for mouse: Mus musculus
Scientific name for E6.5: Not found
Scientific name for human tonsils: Homo sapiens
Scientific name for human tonsils: Not found
Scientific name for .Human tonsils: Not found
Scientific name for .Human tonsils: Not found
Scientific name for Bovine Serum Albumin: Bos taurus
Scientific name for Bovine Serum Albumin: Not found
Scientific name for Bovine Serum Albumin: Not found
Scientific name for human: Homo sapiens
Scientific name for mouse embryos: Mus musculus
Scientific name for mouse embryos: Not found
Scientific name for mouse embryos at 8: Mus musculus
Scientific name for mouse embryos at 8: Not found
Scientific name for mouse embryos at 8: Not found
Scientific name for mouse embryos at 8: Not found
Scientific name for human: Homo sapiens
Scientific name for human rhinovirus: Homo sapiens
Scientific name for human rhinovirus: Enterovirus
Scientific name for Human rhinovirus: Homo sapiens
Scientific name for Human rhinovirus: Enterovirus
Scientific name for herpes simplex virus: Herpes
Scientific name for herpes simplex virus: Not found
Scientific name for herpes simplex virus: Not found
Scientific name for HSV: Not found
Scientific name for HSV-1: Human alphaherpesvirus 1
Scientific name for HSV-1: Human alphaherpesvirus 1
Scientific name for Prestwick Chemical: Not found
Scientific name for Prestwick Chemical: Not found
Scientific name for human: Homo sapiens
Scientific name for human: Homo sapiens
Scientific name for human: Homo sapiens
Scientific name for human cell line: Homo sapiens
Scientific name for human cell line: Not found
Scientific name for human cell line: Not found
Scientific name for N: Not found
Scientific name for o: Not found
Scientific name for t: Not found
Scientific name for f: Not found
Scientific name for o: Not found
Scientific name for u: Not found
Scientific name for n: Not found
Scientific name for d: Not found
Scientific name for human patients: Homo sapiens
Scientific name for human patients: Not found
Scientific name for patients: Not found
Scientific name for Human tissue: Homo sapiens
Scientific name for Human tissue: Not found
Scientific name for Human heart tissue: Homo sapiens
Scientific name for Human heart tissue: Not found
Scientific name for Human heart tissue: Not found
Scientific name for recipients: Not found
Scientific name for donors: Not found
Scientific name for patients: Not found
Scientific name for patient: Not found
Scientific name for human: Homo sapiens
Scientific name for patients: Not found
Scientific name for patient: Not found
Scientific name for patients: Not found
Scientific name for patients: Not found
Scientific name for hearts: Not found
Scientific name for patients: Not found
Scientific name for patients: Not found
Scientific name for N: Not found
Scientific name for o: Not found
Scientific name for t: Not found
Scientific name for f: Not found
Scientific name for o: Not found
Scientific name for u: Not found
Scientific name for n: Not found
Scientific name for d: Not found
Scientific name for human cells: Homo sapiens
Scientific name for human cells: Not found
Scientific name for human cells: Homo sapiens
Scientific name for human cells: Not found
Scientific name for human cells: Homo sapiens
Scientific name for human cells: Not found
Scientific name for gift: Not found
Scientific name for human: Homo sapiens
Scientific name for lentiviral particles: Not found
Scientific name for lentiviral particles: Not found
Scientific name for mouse keratinocytes: Mus musculus
Scientific name for mouse keratinocytes: Not found
Scientific name for CD1 mice: Not found
Scientific name for CD1 mice: Mus sp.
Scientific name for bovine plasma fibronectin: Bos taurus
Scientific name for bovine plasma fibronectin: Not found
Scientific name for bovine plasma fibronectin: Not found
Scientific name for human: Homo sapiens
Scientific name for human: Homo sapiens
Scientific name for human epithelial colorectal adenocarcinoma cell line Caco-2: Homo sapiens
Scientific name for human epithelial colorectal adenocarcinoma cell line Caco-2: Not found
Scientific name for human epithelial colorectal adenocarcinoma cell line Caco-2: Not found
Scientific name for human epithelial colorectal adenocarcinoma cell line Caco-2: Not found
Scientific name for human epithelial colorectal adenocarcinoma cell line Caco-2: Not found
Scientific name for human epithelial colorectal adenocarcinoma cell line Caco-2: Not found
Scientific name for human epithelial colorectal adenocarcinoma cell line Caco-2: Not found
Scientific name for Human epithelial cell line: Homo sapiens
Scientific name for Human epithelial cell line: Not found
Scientific name for Human epithelial cell line: Not found
Scientific name for Human epithelial cell line: Not found
Scientific name for bovine serum: Bos taurus
Scientific name for bovine serum: Not found
Scientific name for Dr: Not found
Scientific name for Mouse: Mus musculus
Scientific name for H&E bone marrow biopsies: Not found
Scientific name for H&E bone marrow biopsies: Not found
Scientific name for H&E bone marrow biopsies: Not found
Scientific name for H&E bone marrow biopsies: Not found
Scientific name for patients: Not found
Scientific name for human bone marrow biopsies: Homo sapiens
Scientific name for human bone marrow biopsies: Not found
Scientific name for human bone marrow biopsies: Not found
Scientific name for human bone marrow biopsies: Not found
Scientific name for human: Homo sapiens
Scientific name for human: Homo sapiens
Scientific name for human kidneys: Homo sapiens
Scientific name for human kidneys: Not found
Scientific name for human fetal kidneys: Homo sapiens
Scientific name for human fetal kidneys: Not found
Scientific name for human fetal kidneys: Not found
Scientific name for thaliana lines: Not found
Scientific name for thaliana lines: Not found
Scientific name for C.: Not found
Scientific name for bovine serum albumin: Bos taurus
Scientific name for bovine serum albumin: Not found
Scientific name for bovine serum albumin: Not found
Scientific name for rat: Rattus norvegicus
Scientific name for guinea-pig: Not found
Scientific name for anti-guinea pig: Not found
Scientific name for anti-guinea pig: Sus scrofa
Scientific name for Alexa Fluor 647: Alexa
Scientific name for Alexa Fluor 647: Not found
Scientific name for Alexa Fluor 647: Not found
Scientific name for bovine serum, 1: Bos taurus
Scientific name for bovine serum, 1: Not found
Scientific name for bovine serum, 1: Not found
Scientific name for bovine serum albumin: Bos taurus
Scientific name for bovine serum albumin: Not found
Scientific name for bovine serum albumin: Not found
Scientific name for mouse anti-B-tubulin IgG1: Mus musculus
Scientific name for mouse anti-B-tubulin IgG1: Not found
Scientific name for mouse anti-B-tubulin IgG1: Not found
Scientific name for donkey anti-mouse IgG: Equus asinus
Scientific name for donkey anti-mouse IgG: Not found
Scientific name for donkey anti-mouse IgG: Not found
Scientific name for Drosophila: Drosophila
Scientific name for Drosophila embryos: Drosophila
Scientific name for Drosophila embryos: Not found
Scientific name for embryos Embryos: Not found
Scientific name for embryos Embryos: Not found
Scientific name for mouse embryonic heart: Mus musculus
Scientific name for mouse embryonic heart: Not found
Scientific name for mouse embryonic heart: Not found
Scientific name for Tribolium castaneum: Tribolium
Scientific name for Tribolium castaneum: Not found
Scientific name for Tribolium castaneum embryos: Tribolium
Scientific name for Tribolium castaneum embryos: Not found
Scientific name for Tribolium castaneum embryos: Not found
Scientific name for bovine serum: Bos taurus
Scientific name for bovine serum: Not found
Scientific name for GE: Ge
Scientific name for bovine serum: Bos taurus
Scientific name for bovine serum: Not found
Scientific name for human: Homo sapiens
Scientific name for Dharmacon cat: Not found
Scientific name for Dharmacon cat: Felis catus
Scientific name for Dharmacon cat: Not found
Scientific name for Dharmacon cat: Felis catus
Scientific name for Dharmacon cat: Not found
Scientific name for Dharmacon cat: Felis catus
Scientific name for N: Not found
Scientific name for o: Not found
Scientific name for t: Not found
Scientific name for f: Not found
Scientific name for o: Not found
Scientific name for u: Not found
Scientific name for n: Not found
Scientific name for d: Not found
Scientific name for Bioneer: Not found
Scientific name for KOs: Not found
Scientific name for zebrafish embryo: Danio rerio
Scientific name for zebrafish embryo: Not found
Scientific name for zebrafish: Danio rerio
Scientific name for human cells: Homo sapiens
Scientific name for human cells: Not found
Scientific name for bovine serum: Bos taurus
Scientific name for bovine serum: Not found
Scientific name for mycoplasma: Mycoplasma
Scientific name for N: Not found
Scientific name for o: Not found
Scientific name for t: Not found
Scientific name for f: Not found
Scientific name for o: Not found
Scientific name for u: Not found
Scientific name for n: Not found
Scientific name for d: Not found
Scientific name for human: Homo sapiens
Scientific name for human: Homo sapiens
Scientific name for human O+ erythrocytes: Homo sapiens
Scientific name for human O+ erythrocytes: Not found
Scientific name for human O+ erythrocytes: Not found
Scientific name for 5 Âµg/ml wheat germ agglutinin: Not found
Scientific name for 5 Âµg/ml wheat germ agglutinin: Not found
Scientific name for 5 Âµg/ml wheat germ agglutinin: Triticum aestivum
Scientific name for 5 Âµg/ml wheat germ agglutinin: Not found
Scientific name for 5 Âµg/ml wheat germ agglutinin: Not found
Scientific name for mice: Mus sp.
Scientific name for mice: Mus sp.
Scientific name for mouse: Mus musculus
Scientific name for mice: Mus sp.
Scientific name for Mice: Mus sp.
Scientific name for mice: Mus sp.
Scientific name for mouse: Mus musculus
Scientific name for human T and: Homo sapiens
Scientific name for human T and: Not found
Scientific name for human T and: Not found
Scientific name for immunodeficient patients: Not found
Scientific name for immunodeficient patients: Not found
Scientific name for donors: Not found
Scientific name for patients: Not found
Scientific name for human serum: Homo sapiens
Scientific name for human serum: Not found
Scientific name for donors: Not found
Scientific name for male: Not found
Scientific name for female: Not found
Scientific name for human breast epithelial cell lines: Homo sapiens
Scientific name for human breast epithelial cell lines: Not found
Scientific name for human breast epithelial cell lines: Not found
Scientific name for human breast epithelial cell lines: Not found
Scientific name for human breast epithelial cell lines: Not found
Scientific name for patient tumors: Not found
Scientific name for patient tumors: Not found
Scientific name for patient tumor cells: Not found
Scientific name for patient tumor cells: Not found
Scientific name for patient tumor cells: Not found
Scientific name for human: Homo sapiens
Scientific name for human: Homo sapiens
Scientific name for mouse melanomas: Mus musculus
Scientific name for mouse melanomas: Not found
Scientific name for Mice: Mus sp.
Scientific name for 14-wk-old male C57/Bl6 J mice: Not found
Scientific name for 14-wk-old male C57/Bl6 J mice: Not found
Scientific name for 14-wk-old male C57/Bl6 J mice: Not found
Scientific name for 14-wk-old male C57/Bl6 J mice: Not found
Scientific name for 14-wk-old male C57/Bl6 J mice: Mus sp.
Scientific name for 5 x10^4 to 2 x10^5 cells: Not found
Scientific name for 5 x10^4 to 2 x10^5 cells: Not found
Scientific name for 5 x10^4 to 2 x10^5 cells: Not found
Scientific name for 5 x10^4 to 2 x10^5 cells: Not found
Scientific name for 5 x10^4 to 2 x10^5 cells: Not found
Scientific name for 5 x10^4 to 2 x10^5 cells: Not found
Scientific name for mice: Mus sp.
Scientific name for mouse: Mus musculus
Scientific name for eGFP OT1 CTL: Not found
Scientific name for eGFP OT1 CTL: Not found
Scientific name for eGFP OT1 CTL: Not found
Scientific name for N: Not found
Scientific name for o: Not found
Scientific name for t: Not found
Scientific name for f: Not found
Scientific name for o: Not found
Scientific name for u: Not found
Scientific name for n: Not found
Scientific name for d: Not found
Scientific name for green' channel: Not found
Scientific name for green' channel: Not found
Scientific name for N: Not found
Scientific name for o: Not found
Scientific name for t: Not found
Scientific name for f: Not found
Scientific name for o: Not found
Scientific name for u: Not found
Scientific name for n: Not found
Scientific name for d: Not found
Scientific name for N: Not found
Scientific name for o: Not found
Scientific name for t: Not found
Scientific name for f: Not found
Scientific name for o: Not found
Scientific name for u: Not found
Scientific name for n: Not found
Scientific name for d: Not found
Scientific name for N: Not found
Scientific name for o: Not found
Scientific name for t: Not found
Scientific name for f: Not found
Scientific name for o: Not found
Scientific name for u: Not found
Scientific name for n: Not found
Scientific name for d: Not found
Scientific name for ICR: Not found
Scientific name for ICR: Not found
Scientific name for human fibroblasts: Homo sapiens
Scientific name for human fibroblasts: Not found
Scientific name for Human: Homo sapiens
Scientific name for Addgene: Not found
Scientific name for Abcam: Not found
Scientific name for Alexa-488 anti-rabbit: Not found
Scientific name for Alexa-488 anti-rabbit: Not found
Scientific name for Hole: Not found
Scientific name for N: Not found
Scientific name for o: Not found
Scientific name for t: Not found
Scientific name for f: Not found
Scientific name for o: Not found
Scientific name for u: Not found
Scientific name for n: Not found
Scientific name for d: Not found
Scientific name for N: Not found
Scientific name for o: Not found
Scientific name for t: Not found
Scientific name for f: Not found
Scientific name for o: Not found
Scientific name for u: Not found
Scientific name for n: Not found
Scientific name for d: Not found
Scientific name for human: Homo sapiens
Scientific name for human: Homo sapiens
Scientific name for human tissues: Homo sapiens
Scientific name for human tissues: Not found
Scientific name for human body: Homo sapiens
Scientific name for human body: Not found
Scientific name for ab13970: Not found
Scientific name for Abcam: Not found
Scientific name for human embryonic arterial valves: Homo sapiens
Scientific name for human embryonic arterial valves: Not found
Scientific name for human embryonic arterial valves: Not found
Scientific name for human embryonic arterial valves: Not found
Scientific name for human embryonic arterial valves: Homo sapiens
Scientific name for human embryonic arterial valves: Not found
Scientific name for human embryonic arterial valves: Not found
Scientific name for human embryonic arterial valves: Not found
Scientific name for mouse: Mus musculus
Scientific name for lentiviral: Not found
Scientific name for lentivirus: Lentivirus
Scientific name for human: Homo sapiens
Scientific name for human rhinovirus: Homo sapiens
Scientific name for human rhinovirus: Enterovirus
Scientific name for herpes simplex virus: Herpes
Scientific name for herpes simplex virus: Not found
Scientific name for herpes simplex virus: Not found
Scientific name for HSV: Not found
Scientific name for HSV-1: Human alphaherpesvirus 1
Scientific name for Prestwick Chemical: Not found
Scientific name for Prestwick Chemical: Not found
Scientific name for mouse: Mus musculus
Scientific name for bovine serum: Bos taurus
Scientific name for bovine serum: Not found
Scientific name for Jackson ImmunoResearch: Not found
Scientific name for Jackson ImmunoResearch: Not found
Scientific name for Abcam ab4448: Not found
Scientific name for Abcam ab4448: Not found
Scientific name for channel-specific: Not found
Scientific name for .Human epithelial cancer U2OS: Not found
Scientific name for .Human epithelial cancer U2OS: Not found
Scientific name for .Human epithelial cancer U2OS: Cancer
Scientific name for .Human epithelial cancer U2OS: Not found
Scientific name for human fibroblasts: Homo sapiens
Scientific name for human fibroblasts: Not found
Scientific name for mouse embryos: Mus musculus
Scientific name for mouse embryos: Not found
Scientific name for mouse embryos                                      : Mus musculus
Scientific name for mouse embryos                                      : Not found
Scientific name for mouse erythroid: Mus musculus
Scientific name for mouse erythroid: Not found
Scientific name for mouse alpha-globin: Mus musculus
Scientific name for mouse alpha-globin: Not found
Scientific name for mouse erythroblasts: Mus musculus
Scientific name for mouse erythroblasts: Not found
Scientific name for mouse: Mus musculus
Scientific name for C57BL/6 mouse embryos: Not found
Scientific name for C57BL/6 mouse embryos: Mus musculus
Scientific name for C57BL/6 mouse embryos: Not found
Scientific name for rabbit IgG: Oryctolagus cuniculus
Scientific name for rabbit IgG: Not found
Scientific name for Jackson Laboratories: Not found
Scientific name for Jackson Laboratories: Not found
Scientific name for mouse fetal liver: Mus musculus
Scientific name for mouse fetal liver: Not found
Scientific name for mouse fetal liver: Not found
Scientific name for CTTCCTAGGGGTCCCAGATGCCGCCTGCCA: Not found
Scientific name for rabbit anti-sheep FITC [: Oryctolagus cuniculus
Scientific name for rabbit anti-sheep FITC [: Not found
Scientific name for rabbit anti-sheep FITC [: Not found
Scientific name for rabbit anti-sheep FITC [: Not found
Scientific name for CD1 mouse: Not found
Scientific name for CD1 mouse: Mus musculus
Scientific name for mice: Mus sp.
Scientific name for human breast tumors: Homo sapiens
Scientific name for human breast tumors: Not found
Scientific name for human breast tumors: Not found
Scientific name for E. coli: Not found
Scientific name for E. coli: Not found
Scientific name for gift: Not found
Scientific name for zebrafish embryo: Danio rerio
Scientific name for zebrafish embryo: Not found
Scientific name for zebrafish tailbud: Danio rerio
Scientific name for zebrafish tailbud: Not found
Scientific name for zebrafish: Danio rerio
Scientific name for ATCC-HTB-96: Not found
Scientific name for human: Homo sapiens
Scientific name for rabbit polyclonal antibody: Oryctolagus cuniculus
Scientific name for rabbit polyclonal antibody: Not found
Scientific name for rabbit polyclonal antibody: Not found
Scientific name for Invitrogen; 1: Not found

In [29]:
for i, item in dfs.iterrows():
    if isinstance(item['Study_Organism'], str) and item['Study_Organism'].strip() != '':
        real_specie = item['Study_Organism']
        scispacy_specie = item['Species_Scientific_Name_SciSpacy']

        if real_specie in scispacy_specie:

            print('The real species is in SciSpacy')
            dfs.at[i, 'Specie_found_Scispacy'] = 'Yes'
        else:
            print('The real species is NOT in SciSpacy')
            dfs.at[i, 'Specie_found_Scispacy'] = 'No'
    else:
        print('No real species to check in SciSpacy')
        dfs.at[i, 'Specie_found_Scispacy'] = 'No species provided'

The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
No real species to check in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
No real species to check in SciSpacy
No real species to check in SciSpacy
The real species is in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
No real species to check in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
No real species to check in SciSpacy
The real species is NOT in SciSpacy
The real species is in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
No real species to check in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy
The real species is NOT in SciSpacy

In [30]:
dfs['Specie_found_Scispacy'].value_counts()

Specie_found_Scispacy
No                     117
Yes                      7
No species provided      6
Name: count, dtype: int64

In [31]:

# Use a pipeline for question answering with BioBERT
# This pipeline is used to answer questions based on the context provided.
# It uses the BioBERT model trained on the SQuAD dataset for question answering.
# The model is loaded with the device set to 'mps' for MacOS GPU support
# and is used to answer questions related to biomedical texts.
# The model is specifically designed for question answering tasks in the biomedical domain.
# ------------------------------------------------------------

qa_pipeline_biobert = pipeline(
    "question-answering",
    model="dmis-lab/biobert-large-cased-v1.1-squad", # SQuAD stands for specific question answering dataset
    tokenizer="dmis-lab/biobert-large-cased-v1.1-squad",
    device = 'cuda' # MPS if the GPU version in MacOS
)

Device set to use cuda

In [32]:
for i, item in dfs.iterrows():
    specie_found = item['Specie_found_Scispacy']

    if specie_found.startswith("No"):
        
        text = item['Description_combined']
        question = 'what species was used in the experiment?'

        result = qa_pipeline_biobert(question=question, context=text)
        print(f"Row {i}: {result['answer']}")
        dfs.at[i, 'Species_BioBERT'] = result['answer']

    else:
        print(f"Row {i}: The species was already found in the previous steps.")

Row 0: yeast
Row 1: mouse
Row 2: The species was already found in the previous steps.
Row 3: human
Row 4: human
Row 5: mouse
Row 6: 10 Î¼l
Row 7: human
Row 8: Diplophyllum taxifolium

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

Row 9: prisoners
Row 10: cell lines
Row 11: Staphylococcus aureus
Row 12: budding yeast
Row 13: The species was already found in the previous steps.
Row 14: U2OS cell line
Row 15: mouse
Row 16: human
Row 17: human
Row 18: Mouse
Row 19: human
Row 20: Arabidopsis thaliana
Row 21: mouse
Row 22: Drosophila
Row 23: mouse
Row 24: Tribolium castaneum
Row 25: Fetal bovine
Row 26: .
Row 27: TLOs
Row 28: fission yeast
Row 29: zebrafish
Row 30: U2OS
Row 31: U-2 OS cells
Row 32: P. falciparum
Row 33: The species was already found in the previous steps.
Row 34: human
Row 35: Arabidopsis
Row 36: The species was already found in the previous steps.
Row 37: human
Row 38: Mice
Row 39: mammalian cells
Row 40: we seeded the cell pool in a single well of 384-well plate
Row 41: bacteria
Row 42: U2OS
Row 43: XX mESCs
Row 44: rabbit
Row 45: Tukeyâs
Row 46: METABRIC cohort
Row 47: human
Row 48: goat
Row 49: mouse
Row 50: reactive oxygen species (ROS
Row 51: mouse
Row 52: cold-water fish
Row 53: Human epithelial cancer U2OS and cervical cancer
Row 54: mouse
Row 55: The species was already found in the previous steps.
Row 56: mice
Row 57: E. coli
Row 58: yeast
Row 59: zebrafish
Row 60: .
Row 61: Arabidopsis
Row 62: HeLa
Row 63: Small intestinal crypts
Row 64: nan .HeLa Ohio cells
Row 65: human
Row 66: cells
Row 67: mouse
Row 68: nan .U2OS
Row 69: human
Row 70: budding yeast
Row 71: Saccharomyces cerevisiae
Row 72: mice
Row 73: fetal bovine
Row 74: human
Row 75: Japan
Row 76: S. cerevisiae
Row 77: MATa
Row 78: HIV-1
Row 79: yeast
Row 80: nan .HeLa
Row 81: yeast
Row 82: zebrafish
Row 83: human
Row 84: murine
Row 85: The species was already found in the previous steps.
Row 86: yeast
Row 87: rabbit
Row 88: thallose liverworts
Row 89: Cells
Row 90: mouse
Row 91: mouse
Row 92: mice
Row 93: human
Row 94: adult mouse
Row 95: mouse
Row 96: human
Row 97: capsid-like particles
Row 98: nan .A549 ATCC (CCL-185)
Row 99: RNA-FISH
Row 100: sea urchin
Row 101: mouse
Row 102: murine and human
Row 103: Mouse
Row 104: The species was already found in the previous steps.
Row 105: silicone elastomer
Row 106: honey bees
Row 107: human
Row 108: nan
Row 109: U-2 OS human osteosarcoma cell line
Row 110: FFPE
Row 111: fetal bovine
Row 112: Drosophila melanogaster
Row 113: mice
Row 114: nan .HeLa
Row 115: Drosophila
Row 116: fetal bovine
Row 117: siRNA
Row 118: HeLa cells
Row 119: homo sapiens
Row 120: Escherichia coli
Row 121: yeast
Row 122: mouse
Row 123: plankton
Row 124: .
Row 125: mouse
Row 126: mouse
Row 127: human
Row 128: R. glauca, R. sorocarpa,
Row 129: yeast

In [33]:
# Creating a new column with the scientific names of the species extracted from the Species_BioBERT column
# This column will be used to store the scientific names of the species extracted from the Species_BioBERT column.
# It uses the EBI taxonomy REST API to get the scientific names of the species.
# It iterates over the Species_BioBERT column, splits the species names, and queries the EBI taxonomy REST API for each species name.
# The scientific names are stored in a list and added to the Species_Scientific_Name_BioBERT column.
# ------------------------------------------------------------

for i, item in dfs.iterrows():
    list_species = item['Species_BioBERT']
    #list_species_scientific_name = []

    if isinstance(list_species, str):
        list_species = list_species.split(', ')
        #print(list_species)

        if list_species != []:
        
            #print(list_species)
            for x in list_species:
                #print(x)

                url = f'https://www.ebi.ac.uk/ena/taxonomy/rest/any-name/{x}'
                    #print(url)

                response = requests.get(url)
                    #print(response.status_code)
                if response.status_code == 200:
                    data = response.json()
                    #print(data)
                    if data:
                        scientific_name = data[0]['scientificName']

                        #list_species_scientific_name.append(scientific_name)
                        print(f"Scientific name for {x}: {scientific_name}")

            dfs.at[i, 'Species_Scientific_Name_BioBERT'] = str(scientific_name)
        else:
            dfs.at[i, 'Species_Scientific_Name_BioBERT'] = 'Not found'

Scientific name for mouse: Mus musculus
Scientific name for human: Homo sapiens
Scientific name for human: Homo sapiens
Scientific name for mouse: Mus musculus
Scientific name for human: Homo sapiens
Scientific name for Diplophyllum taxifolium: Diplophyllum taxifolium
Scientific name for Staphylococcus aureus: Staphylococcus aureus
Scientific name for mouse: Mus musculus
Scientific name for human: Homo sapiens
Scientific name for human: Homo sapiens
Scientific name for Mouse: Mus musculus
Scientific name for human: Homo sapiens
Scientific name for Arabidopsis thaliana: Arabidopsis thaliana
Scientific name for mouse: Mus musculus
Scientific name for Drosophila: Drosophila
Scientific name for mouse: Mus musculus
Scientific name for Tribolium castaneum: Tribolium castaneum
Scientific name for fission yeast: Schizosaccharomyces pombe
Scientific name for zebrafish: Danio rerio
Scientific name for human: Homo sapiens
Scientific name for Arabidopsis: Arabidopsis
Scientific name for human: Homo sapiens
Scientific name for Mice: Mus sp.
Scientific name for bacteria: Bacteria
Scientific name for rabbit: Oryctolagus cuniculus
Scientific name for human: Homo sapiens
Scientific name for goat: Capra hircus
Scientific name for mouse: Mus musculus
Scientific name for mouse: Mus musculus
Scientific name for mouse: Mus musculus
Scientific name for mice: Mus sp.
Scientific name for E. coli: Escherichia coli
Scientific name for zebrafish: Danio rerio
Scientific name for Arabidopsis: Arabidopsis
Scientific name for human: Homo sapiens
Scientific name for mouse: Mus musculus
Scientific name for human: Homo sapiens
Scientific name for Saccharomyces cerevisiae: Saccharomyces cerevisiae
Scientific name for mice: Mus sp.
Scientific name for human: Homo sapiens
Scientific name for S. cerevisiae: Saccharomyces cerevisiae
Scientific name for MATa: Mata
Scientific name for HIV-1: Human immunodeficiency virus 1
Scientific name for zebrafish: Danio rerio
Scientific name for human: Homo sapiens
Scientific name for rabbit: Oryctolagus cuniculus
Scientific name for mouse: Mus musculus
Scientific name for mouse: Mus musculus
Scientific name for mice: Mus sp.
Scientific name for human: Homo sapiens
Scientific name for mouse: Mus musculus
Scientific name for human: Homo sapiens
Scientific name for sea urchin: Echinoidea
Scientific name for mouse: Mus musculus
Scientific name for Mouse: Mus musculus
Scientific name for honey bees: Apinae
Scientific name for human: Homo sapiens
Scientific name for Drosophila melanogaster: Drosophila melanogaster
Scientific name for mice: Mus sp.
Scientific name for Drosophila: Drosophila
Scientific name for homo sapiens: Homo sapiens
Scientific name for Escherichia coli: Escherichia coli
Scientific name for mouse: Mus musculus
Scientific name for mouse: Mus musculus
Scientific name for mouse: Mus musculus
Scientific name for human: Homo sapiens

In [34]:
dfs['Species_Scientific_Name_BioBERT'] = dfs['Species_Scientific_Name_BioBERT'].astype(str)

In [35]:
dfs

,Comment[IDR_Study_Accession],Study_Title,Study_Type,Study_Type_Term_Source_REF,Study_Type_Term_Accession,Study_Description,Study_Organism,Study_Public_Release_Date,Study_PubMed_ID,Study_Publication_Title,...,Protocol_Type_Term_Source_REF,Protocol_Type_Term_Accession,Protocol_Description,Description_combined,Entities_SpaCy,Species_SpaCy,Species_Scientific_Name_SciSpacy,Specie_found_Scispacy,Species_BioBERT,Species_Scientific_Name_BioBERT
0,idr0047,A microscopy data set of discrete spatial and ...,fluorescence in situ hybridization,NCIT,NCIT_C17563,We report a comprehensive single cell dataset ...,Saccharomyces cerevisiae,2019-01-16,31209217,Multiplex RNA single molecule FISH of inducibl...,...,EFO EFO,EFO_0003789 EFO_0003969,"CSM, 30C 0.2M NaCl, step TRANS: brightfield of...",We report a comprehensive single cell dataset ...,"{'CELL': ['cell', 'cerevisiae', 'cells', 'cell...",[Excelitas],[],No,yeast,Not found
1,idr0038,Ex vivo live cell tracking in kidney organoids...,time-lapse imaging,OMIT,OMIT_0027490,We have adapted the mouse kidney rudiment assa...,Mus musculus,2017-12-04,30048451,Ex vivo live cell tracking in kidney organoids...,...,EFO,EFO_0003789,"""Kidneys were isolated from E13.5 embryos afte...",We have adapted the mouse kidney rudiment assa...,"{'ORGANISM': ['mouse kidney rudiment', 'E13.5 ...","[mouse kidney rudiment, E13.5 embryonic kidney...","['Mus musculus', 'Mus musculus', 'Mus musculus...",No,mouse,Mus musculus
2,idr0146,Time lapse imaging of mesoderm and early cardi...,time-lapse imaging ...,OMIT,OMIT_0027490,Using four-dimensional whole-embryo light shee...,Mus musculus,2023-02-06,36736300,Graded mesoderm assembly governs cell fate and...,...,EFO EFO,EFO_0003789 EFO_0003969 ...,see attached DominguezMH Embryo Culture.pdf se...,Using four-dimensional whole-embryo light shee...,"{'ORGANISM': ['murine cardiac', 'mouse', 'E6.5...","[murine cardiac, mouse, E6.5]",['Mus musculus'],Yes,NaN,nan
3,idr0054,Imaging Mass Cytometry of human tonsil sections,image cytometry,OMIT,OMIT_0019157,We analysed the in situ localisation of immune...,Homo sapiens,2019-03-19,31072818,Human lymphoid organ cDC2 and macrophages play...,...,EFO EFO,EFO_0003789 EFO_0003969,Human tonsils were fixed in 4% paraformaldehyd...,We analysed the in situ localisation of immune...,"{'CELL': ['immune cell'], 'ORGANISM': ['human ...","[human tonsils, .Human tonsils, Bovine Serum A...","['Homo sapiens', 'Bos taurus']",No,human,Homo sapiens
4,idr0149,Cohesin-mediated DNA loop extrusion resolves s...,protein localization ...,EFO,GO_0008104,Genetic information is stored in linear DNA mo...,Homo sapiens,2023-08-17,37357575,Cohesin-mediated DNA loop extrusion resolves s...,...,EFO EFO,EFO_0003789 EFO_0003969 ...,To assess nuclear Sororin fluorescence in Soro...,Genetic information is stored in linear DNA mo...,"{'CELLULAR_COMPONENT': ['DNA', 'DNA', 'nuclear...",[human],['Homo sapiens'],No,human,Homo sapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,idr0155,A new method for reliably detecting single flu...,protein localization,EFO,GO_0008104,Super-resolution and single-molecule microscop...,Homo sapiens,2024-03-05,,RASP: Optimal single puncta detection in compl...,...,EFO,EFO_0003969,Tissue sections were incubated with primary an...,Super-resolution and single-molecule microscop...,"{'CELL': ['cells', 'cell', 'cells', 'cellular'...","[human brain, patient]",['Homo sapiens'],No,mouse,Mus musculus
126,idr0044,In Toto Imaging and Reconstruction of Post-Imp...,time-lapse imaging,OMIT,OMIT_0027490,The mouse embryo has long been central to the ...,Mus musculus,2018-11-29,30318151,In Toto Imaging and Reconstruction of Post-Imp...,...,EFO N/A,EFO_0001746 N/A,See attached methods N/A See attached methods ...,The mouse embryo has long been central to the ...,"{'ORGANISM': ['mouse embryo', 'mouse', 'mouse'...","[mouse embryo, mouse, mouse, mouse, E6.5]","['Mus musculus', 'Mus musculus', 'Mus musculus...",No,mouse,Mus musculus
127,idr0093,High content genome-wide siRNA screen to inves...,high content screen,EFO,EFO_0007550,Coordination of RNA abundance and transcriptio...,Homo sapiens,2021-03-17,,High content genome-wide siRNA screen to inves...,...,EFO EFO EFO EFO EFO,EFO_0003789 EFO_0003969 EFO_0007571 EFO_000757...,5nl of 5Î¼M siRNAs from the Ambion Silencer Se...,Coordination of RNA abundance and transcriptio...,"{'CELL': ['cell', 'cell', 'cells', 'single-cel...",[human cells],['Homo sapiens'],No,human,Homo sapiens
128,idr0137,Reference BioImaging dataset to assess the phe...,phenotype,EFO,EFO_0000651,A reference dataset containing macroscopic and...,Riccia glauca Riccia sorocarpa Riccia warnstor...,2023-01-17,,Data integration in biodiversity - A principal...,...,EFO EFO,EFO_0003789 EFO_0003969 ...,,A reference dataset containing macroscopic and...,"{'CANCER': ['glauca', 'specimens', 'CB3', 'CR3...","[Riccia glauca, TSV]","['Riccia', 'Tobacco streak virus']",No,"R. glauca, R. sorocarpa,",Homo sapiens
129,idr0027,High resolution imaging reveals heterogeneity ...,time-lapse imaging,OMIT,OMIT_0027490,We established a work flow for measuring the d...,Saccharomyces cerevisiae,2016-11-01,27609610,High resolution imaging reveals heterogeneity ...,...,EFO,EFO_0003789,The S. cerevisiae strains in this study are su...,We established a work flow for measuring the d...,"{'CELLULAR_COMPONENT': ['chromatin', 'chromati...",Not found,[],No,yeast,Homo sapiens

In [36]:
dfs['Species_Scientific_Name_BioBERT'][4] == 'Homo sapiens'

True

In [37]:
for i, item in dfs.iterrows():
    specie_found = item['Specie_found_Scispacy']

    if specie_found.startswith("No"):

        if isinstance(item['Study_Organism'], str) and item['Study_Organism'].strip() != '':
            real_specie = item['Study_Organism'][0]
            bert_specie = item['Species_Scientific_Name_BioBERT'][0]

            if real_specie in bert_specie:

                print('The real species is in the bert')
                dfs.at[i, 'Specie_found_biobert'] = 'Yes'
            else:
                print('The real species is NOT in the response.')
                dfs.at[i, 'Specie_found_biobert'] = 'No'
        else:
            print('No real species to check in the response.')
            dfs.at[i, 'Specie_found_biobert'] = 'No species provided'

The real species is NOT in the response.
The real species is in the bert
The real species is in the bert
The real species is in the bert
The real species is in the bert
The real species is NOT in the response.
The real species is in the bert
The real species is in the bert
The real species is NOT in the response.
The real species is NOT in the response.
The real species is in the bert
The real species is in the bert
The real species is NOT in the response.
The real species is in the bert
The real species is in the bert
The real species is in the bert
No real species to check in the response.
The real species is in the bert
The real species is in the bert
The real species is NOT in the response.
The real species is in the bert
The real species is in the bert
The real species is in the bert
The real species is NOT in the response.
The real species is NOT in the response.
The real species is NOT in the response.
The real species is in the bert
The real species is in the bert
The real species is NOT in the response.
The real species is NOT in the response.
The real species is NOT in the response.
The real species is in the bert
The real species is in the bert
The real species is in the bert
The real species is in the bert
The real species is NOT in the response.
The real species is NOT in the response.
The real species is NOT in the response.
The real species is NOT in the response.
The real species is NOT in the response.
The real species is NOT in the response.
The real species is NOT in the response.
The real species is NOT in the response.
The real species is in the bert
The real species is NOT in the response.
The real species is NOT in the response.
The real species is NOT in the response.
The real species is NOT in the response.
The real species is NOT in the response.
No real species to check in the response.
No real species to check in the response.
The real species is NOT in the response.
The real species is in the bert
The real species is NOT in the response.
The real species is in the bert
The real species is NOT in the response.
The real species is in the bert
The real species is NOT in the response.
The real species is NOT in the response.
The real species is NOT in the response.
The real species is in the bert
The real species is in the bert
The real species is in the bert
The real species is NOT in the response.
The real species is in the bert
The real species is NOT in the response.
The real species is in the bert
The real species is NOT in the response.
The real species is NOT in the response.
The real species is in the bert
The real species is in the bert
The real species is in the bert
The real species is NOT in the response.
The real species is in the bert
The real species is NOT in the response.
The real species is in the bert
The real species is NOT in the response.
The real species is in the bert
The real species is in the bert
The real species is in the bert
The real species is NOT in the response.
The real species is NOT in the response.
The real species is NOT in the response.
The real species is NOT in the response.
The real species is in the bert
The real species is in the bert
No real species to check in the response.
The real species is in the bert
The real species is NOT in the response.
The real species is in the bert
The real species is in the bert
The real species is in the bert
The real species is in the bert
The real species is in the bert
The real species is NOT in the response.
The real species is NOT in the response.
No real species to check in the response.
The real species is in the bert
The real species is NOT in the response.
The real species is in the bert
The real species is in the bert
The real species is in the bert
The real species is in the bert
The real species is in the bert
The real species is in the bert
The real species is in the bert
The real species is in the bert
The real species is NOT in the response.
No real species to check in the response.
The real species is NOT in the response.
The real species is NOT in the response.
The real species is NOT in the response.
The real species is in the bert
The real species is in the bert
The real species is NOT in the response.
The real species is in the bert
The real species is NOT in the response.
The real species is NOT in the response.
The real species is NOT in the response.
The real species is in the bert
The real species is in the bert
The real species is NOT in the response.
The real species is NOT in the response.

In [43]:
dfs['Specie_found_biobert'].value_counts()

Specie_found_biobert
Yes                    61
No                     56
No species provided     6
Name: count, dtype: int64

In [38]:
type(dfs['Specie_found_biobert'][2])

float

In [39]:
dfs

,Comment[IDR_Study_Accession],Study_Title,Study_Type,Study_Type_Term_Source_REF,Study_Type_Term_Accession,Study_Description,Study_Organism,Study_Public_Release_Date,Study_PubMed_ID,Study_Publication_Title,...,Protocol_Type_Term_Accession,Protocol_Description,Description_combined,Entities_SpaCy,Species_SpaCy,Species_Scientific_Name_SciSpacy,Specie_found_Scispacy,Species_BioBERT,Species_Scientific_Name_BioBERT,Specie_found_biobert
0,idr0047,A microscopy data set of discrete spatial and ...,fluorescence in situ hybridization,NCIT,NCIT_C17563,We report a comprehensive single cell dataset ...,Saccharomyces cerevisiae,2019-01-16,31209217,Multiplex RNA single molecule FISH of inducibl...,...,EFO_0003789 EFO_0003969,"CSM, 30C 0.2M NaCl, step TRANS: brightfield of...",We report a comprehensive single cell dataset ...,"{'CELL': ['cell', 'cerevisiae', 'cells', 'cell...",[Excelitas],[],No,yeast,Not found,No
1,idr0038,Ex vivo live cell tracking in kidney organoids...,time-lapse imaging,OMIT,OMIT_0027490,We have adapted the mouse kidney rudiment assa...,Mus musculus,2017-12-04,30048451,Ex vivo live cell tracking in kidney organoids...,...,EFO_0003789,"""Kidneys were isolated from E13.5 embryos afte...",We have adapted the mouse kidney rudiment assa...,"{'ORGANISM': ['mouse kidney rudiment', 'E13.5 ...","[mouse kidney rudiment, E13.5 embryonic kidney...","['Mus musculus', 'Mus musculus', 'Mus musculus...",No,mouse,Mus musculus,Yes
2,idr0146,Time lapse imaging of mesoderm and early cardi...,time-lapse imaging ...,OMIT,OMIT_0027490,Using four-dimensional whole-embryo light shee...,Mus musculus,2023-02-06,36736300,Graded mesoderm assembly governs cell fate and...,...,EFO_0003789 EFO_0003969 ...,see attached DominguezMH Embryo Culture.pdf se...,Using four-dimensional whole-embryo light shee...,"{'ORGANISM': ['murine cardiac', 'mouse', 'E6.5...","[murine cardiac, mouse, E6.5]",['Mus musculus'],Yes,NaN,nan,NaN
3,idr0054,Imaging Mass Cytometry of human tonsil sections,image cytometry,OMIT,OMIT_0019157,We analysed the in situ localisation of immune...,Homo sapiens,2019-03-19,31072818,Human lymphoid organ cDC2 and macrophages play...,...,EFO_0003789 EFO_0003969,Human tonsils were fixed in 4% paraformaldehyd...,We analysed the in situ localisation of immune...,"{'CELL': ['immune cell'], 'ORGANISM': ['human ...","[human tonsils, .Human tonsils, Bovine Serum A...","['Homo sapiens', 'Bos taurus']",No,human,Homo sapiens,Yes
4,idr0149,Cohesin-mediated DNA loop extrusion resolves s...,protein localization ...,EFO,GO_0008104,Genetic information is stored in linear DNA mo...,Homo sapiens,2023-08-17,37357575,Cohesin-mediated DNA loop extrusion resolves s...,...,EFO_0003789 EFO_0003969 ...,To assess nuclear Sororin fluorescence in Soro...,Genetic information is stored in linear DNA mo...,"{'CELLULAR_COMPONENT': ['DNA', 'DNA', 'nuclear...",[human],['Homo sapiens'],No,human,Homo sapiens,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,idr0155,A new method for reliably detecting single flu...,protein localization,EFO,GO_0008104,Super-resolution and single-molecule microscop...,Homo sapiens,2024-03-05,,RASP: Optimal single puncta detection in compl...,...,EFO_0003969,Tissue sections were incubated with primary an...,Super-resolution and single-molecule microscop...,"{'CELL': ['cells', 'cell', 'cells', 'cellular'...","[human brain, patient]",['Homo sapiens'],No,mouse,Mus musculus,No
126,idr0044,In Toto Imaging and Reconstruction of Post-Imp...,time-lapse imaging,OMIT,OMIT_0027490,The mouse embryo has long been central to the ...,Mus musculus,2018-11-29,30318151,In Toto Imaging and Reconstruction of Post-Imp...,...,EFO_0001746 N/A,See attached methods N/A See attached methods ...,The mouse embryo has long been central to the ...,"{'ORGANISM': ['mouse embryo', 'mouse', 'mouse'...","[mouse embryo, mouse, mouse, mouse, E6.5]","['Mus musculus', 'Mus musculus', 'Mus musculus...",No,mouse,Mus musculus,Yes
127,idr0093,High content genome-wide siRNA screen to inves...,high content screen,EFO,EFO_0007550,Coordination of RNA abundance and transcriptio...,Homo sapiens,2021-03-17,,High content genome-wide siRNA screen to inves...,...,EFO_0003789 EFO_0003969 EFO_0007571 EFO_000757...,5nl of 5Î¼M siRNAs from the Ambion Silencer Se...,Coordination of RNA abundance and transcriptio...,"{'CELL': ['cell', 'cell', 'cells', 'single-cel...",[human cells],['Homo sapiens'],No,human,Homo sapiens,Yes
128,idr0137,Reference BioImaging dataset to assess the phe...,phenotype,EFO,EFO_0000651,A reference dataset containing macroscopic and...,Riccia glauca Riccia sorocarpa Riccia warnstor...,2023-01-17,,Data integration in biodiversity - A principal...,...,EFO_0003789 EFO_0003969 ...,,A reference dataset containing macroscopic and...,"{'CANCER': ['glauca', 'specimens', 'CB3', 'CR3...","[Riccia glauca, TSV]","['Riccia', 'Tobacco streak virus']",No,"R. glauca, R. sorocarpa,",Homo sapiens,No
129,idr0027,High resolution imaging reveals heterogeneity ...,time-lapse imaging,OMIT,OMIT_0027490,We established a work flow for measuring the d...,Saccharomyces cerevisiae,2016-11-01,27609610,High resolution imaging reveals heterogeneity ...,...,EFO_0003789,The S. cerevisiae strains in this study are su...,We established a work flow for measuring the d...,"{'CELLULAR_COMPONENT': ['chromatin', 'chromati...",Not found,[],No,yeast,Homo sapiens,No

In [44]:
for row, i in dfs.iterrows():
    value_biobert = str(i['Specie_found_biobert'])
    

    if value_biobert.startswith("No"):
    
        message = [
        {"role": "system", "content": i["Description_combined"]},
        {"role": "user", "content": "Can you tell me which specie was used in this study?"},
        ]

        outputs = pipe(message, max_new_tokens = 256)
        response = outputs[0]["generated_text"][-1]["content"]
        dfs.at[row, 'Species_Llama'] = response
        print(f"Processed row {row} for species extraction.")

        if isinstance(i['Study_Organism'], str) and i['Study_Organism'].strip() != '':

            real_specie = i['Study_Organism'][0]

            if real_specie in response:
                print('The real species is in the response.')
                dfs.at[row, 'Species_found_Llama'] = 'Yes'
            else:
                print('The real species is NOT in the response.')
                dfs.at[row, 'Species_found_Llama'] = 'No'
        else:
            print('No real species to check in the response.')
            dfs.at[row, 'Species_found_Llama'] = 'No species provided'

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 0 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 6 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 9 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 10 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 14 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 18 for species extraction.
No real species to check in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 21 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 25 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 26 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 27 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 30 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 31 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 32 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 39 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 40 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 41 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 42 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 43 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 44 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 45 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 46 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 48 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 49 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 50 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 51 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 52 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 53 for species extraction.
No real species to check in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 54 for species extraction.
No real species to check in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 56 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 58 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 60 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 62 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 63 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 64 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 68 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 70 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 72 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 73 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 77 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 79 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 81 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 86 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 87 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 88 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 89 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 92 for species extraction.
No real species to check in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 94 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 100 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 101 for species extraction.
The real species is NOT in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 102 for species extraction.
No real species to check in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 105 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 114 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 115 for species extraction.
No real species to check in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 116 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 117 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 118 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 121 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 123 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 124 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 125 for species extraction.
The real species is in the response.

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Processed row 128 for species extraction.
The real species is in the response.
Processed row 129 for species extraction.
The real species is in the response.

In [45]:
dfs['Species_found_Llama'].value_counts()

Species_found_Llama
Yes                    39
No                     17
No species provided     6
Name: count, dtype: int64

In [46]:
for row, i in dfs.iterrows():
    value_scipacy = str(i['Specie_found_biobert'])
    value_biobert = str(i['Specie_found_Scispacy'])
    value_lama = str(i['Species_found_Llama'])

    if value_scipacy.startswith("Yes") or value_biobert.startswith("Yes") or value_lama.startswith("Yes"):
        print(f"Row {row}: Species found in one of the methods.")
        dfs.at[row, 'Species_found'] = 'Yes'

    else:
        print(f"Row {row}: Species not found in any method.")
        dfs.at[row, 'Species_found'] = 'No'

Row 0: Species found in one of the methods.
Row 1: Species found in one of the methods.
Row 2: Species found in one of the methods.
Row 3: Species found in one of the methods.
Row 4: Species found in one of the methods.
Row 5: Species found in one of the methods.
Row 6: Species found in one of the methods.
Row 7: Species found in one of the methods.
Row 8: Species found in one of the methods.
Row 9: Species found in one of the methods.
Row 10: Species found in one of the methods.
Row 11: Species found in one of the methods.
Row 12: Species found in one of the methods.
Row 13: Species found in one of the methods.
Row 14: Species not found in any method.
Row 15: Species found in one of the methods.
Row 16: Species found in one of the methods.
Row 17: Species found in one of the methods.
Row 18: Species not found in any method.
Row 19: Species found in one of the methods.
Row 20: Species found in one of the methods.
Row 21: Species found in one of the methods.
Row 22: Species found in one of the methods.
Row 23: Species found in one of the methods.
Row 24: Species found in one of the methods.
Row 25: Species found in one of the methods.
Row 26: Species found in one of the methods.
Row 27: Species not found in any method.
Row 28: Species found in one of the methods.
Row 29: Species found in one of the methods.
Row 30: Species not found in any method.
Row 31: Species not found in any method.
Row 32: Species found in one of the methods.
Row 33: Species found in one of the methods.
Row 34: Species found in one of the methods.
Row 35: Species found in one of the methods.
Row 36: Species found in one of the methods.
Row 37: Species found in one of the methods.
Row 38: Species found in one of the methods.
Row 39: Species found in one of the methods.
Row 40: Species found in one of the methods.
Row 41: Species not found in any method.
Row 42: Species not found in any method.
Row 43: Species not found in any method.
Row 44: Species found in one of the methods.
Row 45: Species not found in any method.
Row 46: Species found in one of the methods.
Row 47: Species found in one of the methods.
Row 48: Species found in one of the methods.
Row 49: Species not found in any method.
Row 50: Species found in one of the methods.
Row 51: Species found in one of the methods.
Row 52: Species found in one of the methods.
Row 53: Species not found in any method.
Row 54: Species not found in any method.
Row 55: Species found in one of the methods.
Row 56: Species not found in any method.
Row 57: Species found in one of the methods.
Row 58: Species found in one of the methods.
Row 59: Species found in one of the methods.
Row 60: Species found in one of the methods.
Row 61: Species found in one of the methods.
Row 62: Species found in one of the methods.
Row 63: Species not found in any method.
Row 64: Species found in one of the methods.
Row 65: Species found in one of the methods.
Row 66: Species found in one of the methods.
Row 67: Species found in one of the methods.
Row 68: Species not found in any method.
Row 69: Species found in one of the methods.
Row 70: Species found in one of the methods.
Row 71: Species found in one of the methods.
Row 72: Species not found in any method.
Row 73: Species found in one of the methods.
Row 74: Species found in one of the methods.
Row 75: Species found in one of the methods.
Row 76: Species found in one of the methods.
Row 77: Species found in one of the methods.
Row 78: Species found in one of the methods.
Row 79: Species found in one of the methods.
Row 80: Species found in one of the methods.
Row 81: Species found in one of the methods.
Row 82: Species found in one of the methods.
Row 83: Species found in one of the methods.
Row 84: Species found in one of the methods.
Row 85: Species found in one of the methods.
Row 86: Species found in one of the methods.
Row 87: Species not found in any method.
Row 88: Species found in one of the methods.
Row 89: Species found in one of the methods.
Row 90: Species found in one of the methods.
Row 91: Species found in one of the methods.
Row 92: Species not found in any method.
Row 93: Species found in one of the methods.
Row 94: Species not found in any method.
Row 95: Species found in one of the methods.
Row 96: Species found in one of the methods.
Row 97: Species found in one of the methods.
Row 98: Species found in one of the methods.
Row 99: Species found in one of the methods.
Row 100: Species not found in any method.
Row 101: Species not found in any method.
Row 102: Species not found in any method.
Row 103: Species found in one of the methods.
Row 104: Species found in one of the methods.
Row 105: Species found in one of the methods.
Row 106: Species found in one of the methods.
Row 107: Species found in one of the methods.
Row 108: Species found in one of the methods.
Row 109: Species found in one of the methods.
Row 110: Species found in one of the methods.
Row 111: Species found in one of the methods.
Row 112: Species found in one of the methods.
Row 113: Species found in one of the methods.
Row 114: Species found in one of the methods.
Row 115: Species not found in any method.
Row 116: Species found in one of the methods.
Row 117: Species found in one of the methods.
Row 118: Species found in one of the methods.
Row 119: Species found in one of the methods.
Row 120: Species found in one of the methods.
Row 121: Species found in one of the methods.
Row 122: Species found in one of the methods.
Row 123: Species found in one of the methods.
Row 124: Species found in one of the methods.
Row 125: Species found in one of the methods.
Row 126: Species found in one of the methods.
Row 127: Species found in one of the methods.
Row 128: Species found in one of the methods.
Row 129: Species found in one of the methods.

In [47]:
dfs['Species_found'].value_counts()

Species_found
Yes    107
No      23
Name: count, dtype: int64

In [56]:
for row, i in dfs.iterrows():
    value_scipacy = i['Specie_found_biobert']
    value_biobert = i['Specie_found_Scispacy']
    value_lama = i['Species_found_Llama']

    if value_scipacy.startswith("Yes") :
        print(f"Row {row}: Species found in SciSpacy and Llama, but not in BioBERT.")

Row 1: Species found in SciSpacy and Llama, but not in BioBERT.
Row 3: Species found in SciSpacy and Llama, but not in BioBERT.
Row 4: Species found in SciSpacy and Llama, but not in BioBERT.
Row 5: Species found in SciSpacy and Llama, but not in BioBERT.
Row 7: Species found in SciSpacy and Llama, but not in BioBERT.
Row 8: Species found in SciSpacy and Llama, but not in BioBERT.
Row 11: Species found in SciSpacy and Llama, but not in BioBERT.
Row 12: Species found in SciSpacy and Llama, but not in BioBERT.
Row 15: Species found in SciSpacy and Llama, but not in BioBERT.
Row 16: Species found in SciSpacy and Llama, but not in BioBERT.
Row 17: Species found in SciSpacy and Llama, but not in BioBERT.
Row 19: Species found in SciSpacy and Llama, but not in BioBERT.
Row 20: Species found in SciSpacy and Llama, but not in BioBERT.
Row 22: Species found in SciSpacy and Llama, but not in BioBERT.
Row 23: Species found in SciSpacy and Llama, but not in BioBERT.
Row 24: Species found in SciSpacy and Llama, but not in BioBERT.
Row 28: Species found in SciSpacy and Llama, but not in BioBERT.
Row 29: Species found in SciSpacy and Llama, but not in BioBERT.
Row 34: Species found in SciSpacy and Llama, but not in BioBERT.
Row 35: Species found in SciSpacy and Llama, but not in BioBERT.
Row 37: Species found in SciSpacy and Llama, but not in BioBERT.
Row 38: Species found in SciSpacy and Llama, but not in BioBERT.
Row 47: Species found in SciSpacy and Llama, but not in BioBERT.
Row 57: Species found in SciSpacy and Llama, but not in BioBERT.
Row 59: Species found in SciSpacy and Llama, but not in BioBERT.
Row 61: Species found in SciSpacy and Llama, but not in BioBERT.
Row 65: Species found in SciSpacy and Llama, but not in BioBERT.
Row 66: Species found in SciSpacy and Llama, but not in BioBERT.
Row 67: Species found in SciSpacy and Llama, but not in BioBERT.
Row 69: Species found in SciSpacy and Llama, but not in BioBERT.
Row 71: Species found in SciSpacy and Llama, but not in BioBERT.
Row 74: Species found in SciSpacy and Llama, but not in BioBERT.
Row 75: Species found in SciSpacy and Llama, but not in BioBERT.
Row 76: Species found in SciSpacy and Llama, but not in BioBERT.
Row 78: Species found in SciSpacy and Llama, but not in BioBERT.
Row 80: Species found in SciSpacy and Llama, but not in BioBERT.
Row 82: Species found in SciSpacy and Llama, but not in BioBERT.
Row 83: Species found in SciSpacy and Llama, but not in BioBERT.
Row 84: Species found in SciSpacy and Llama, but not in BioBERT.
Row 90: Species found in SciSpacy and Llama, but not in BioBERT.
Row 91: Species found in SciSpacy and Llama, but not in BioBERT.
Row 93: Species found in SciSpacy and Llama, but not in BioBERT.
Row 95: Species found in SciSpacy and Llama, but not in BioBERT.
Row 96: Species found in SciSpacy and Llama, but not in BioBERT.
Row 97: Species found in SciSpacy and Llama, but not in BioBERT.
Row 98: Species found in SciSpacy and Llama, but not in BioBERT.
Row 99: Species found in SciSpacy and Llama, but not in BioBERT.
Row 103: Species found in SciSpacy and Llama, but not in BioBERT.
Row 106: Species found in SciSpacy and Llama, but not in BioBERT.
Row 107: Species found in SciSpacy and Llama, but not in BioBERT.
Row 108: Species found in SciSpacy and Llama, but not in BioBERT.
Row 109: Species found in SciSpacy and Llama, but not in BioBERT.
Row 110: Species found in SciSpacy and Llama, but not in BioBERT.
Row 111: Species found in SciSpacy and Llama, but not in BioBERT.
Row 112: Species found in SciSpacy and Llama, but not in BioBERT.
Row 113: Species found in SciSpacy and Llama, but not in BioBERT.
Row 119: Species found in SciSpacy and Llama, but not in BioBERT.
Row 120: Species found in SciSpacy and Llama, but not in BioBERT.
Row 122: Species found in SciSpacy and Llama, but not in BioBERT.
Row 126: Species found in SciSpacy and Llama, but not in BioBERT.
Row 127: Species found in SciSpacy and Llama, but not in BioBERT.