### Dummy data analysis

In [1]:
import os, sys
import io
import numpy as np
import pandas as pd
from ydata_profiling import ProfileReport
from collections import Counter
import json

import matplotlib
matplotlib.style.use('ggplot')
from matplotlib import pyplot as plt

In [2]:
pwd

'/Users/s2531396/Library/CloudStorage/OneDrive-UniversityofEdinburgh/PhD/Code'

In [3]:
data_dir = '/Users/s2531396/Library/CloudStorage/OneDrive-UniversityofEdinburgh/PhD/Code'

In [4]:
data = json.load(open('example3.json'))
data['Experiment']

[{'id': '26940',
  'General_description': 'identify zebrafish pld6 as a novel germline-specific gene by cross-analyzing different',
  'Purpose': 'The supernatants obtained from the two low-speed spins are pooled and then centrifuged at 10,000 Xg for 15min. Crude mitochondria, which are recovered in the pellet, are resuspended in extraction buffer (approximately 20–25 μL) (or wash twice using extraction buffer and centrifuge at 7000g)Mitochondria preparation from cell.',
  'Description': 'Remove the medium from the cells and wash the cells once with PB',
  'Open_Access': 'under CC_BY license',
  'Comments': 'Mitochondria preparation from cell Glassware and buffer must be precooled in an ice-bath. Steps 3– 9 must be performed at 0– 4 ° C to minimize the activation of damaging phospholipases an',
  'collection_date': '2023-11-10',
  'Authors': 'ma dongcheng',
  'Institutions/Fundings': 'suda,',
  'Data_category': 'Behaviour (e.g. wheel running)',
  'Technique': 'Other',
  'Technique_details': 'Unespecified',
  'Data_size_Mb': 10,
  'Species': 'Danio rerio',
  'Data_curator': None},
 {'id': '19235',
  'General_description': 'Role of PRR7 in control of the CCA1 promoter',
  'Purpose': 'To test whether PRR7 is required for circadian input to the CCA1 promoter in shoots and roots',
  'Description': 'In previous experiments several clock mutations were found to have different effects on shoots and roots. In these experiments mature prr7-3 plants expressing CCA1::LUC were grown on vertical agar plates as described previously. LUC activity in shoots and roots was monitored over 2 full days in LD cycles (12:12) followed by 4 days in LL.',
  'Open_Access': 'under CC_BY license',
  'Comments': 'Details are as in Bordage et al (2016) New Phytol. 212, 136-149',
  'collection_date': '2021-05-20',
  'Authors': 'Hugh Nimmo,',
  'Institutions/Fundings': 'University of Glasgow, BBSRC [BB/K006835/1]',
  'Data_category': 'Expression reporter (e.g. Luc/GFP-imaging)',
  'Technique': 'Luciferase luminescence (Photek 225/18 CCD camera)',
  'Technique_details': 'Mature plants were on square vertical agar plates at 20°C with shoot and root compartments separated and images recorded as in Bordage et al 2016. Plants were sprayed with luciferin 15 h before the start of data collection. Images were recorded every 1.5 h for 2 days in LD and 4 days in LL.',
  'Data_size_Mb': 50,
  'Species': 'Arabidopsis thaliana',
  'Data_curator': None},
 {'id': '17264',
  'General_description': 'CCA1:LUC',
  'Purpose': 'Analysis CCA1:LUC period and amplitude changes. 111111111',
  'Description': None,
  'Open_Access': 'under CC_BY license',
  'Comments': None,
  'collection_date': '2020-11-11',
  'Authors': 'Flash Light,',
  'Institutions/Fundings': 'University of Edinburgh,',
  'Data_category': 'Expression reporter (e.g. Luc/GFP-imaging)',
  'Technique': 'Luciferase luminescence',
  'Technique_details': 'Unespecified',
  'Data_size_Mb': 30,
  'Species': 'Arabidopsis thaliana',
  'Data_curator': None},
 {'id': '22843',
  'General_description': 'Figure 3/5 - Cry1-Luc + pSyn1.Cry1(TAG)::EGFP, 10mM AlkK',
  'Purpose': 'McManus et al, Figure 3: Translational switching of CRY1 expression allows reversible and dose-dependent control of period and amplitude of the TTFL of wild-type SCN.',
  'Description': 'Cry1-Luc SCN transduced with pSyn1.Cry1(TAG)::EGFP + pSyn1.PylRS, treated with 10mM AlkK All Treated with 10mM AlkK at 144-150h. Treatment washout: 41-51 - 377-383, 55-60 - 415-419',
  'Open_Access': 'under CC_BY license',
  'Comments': None,
  'collection_date': '2022-05-25',
  'Authors': 'David McManus,',
  'Institutions/Fundings': 'MRC LMB,',
  'Data_category': 'Expression reporter (e.g. Luc/GFP-imaging)',
  'Technique': 'Luciferase luminescence',
  'Technique_details': 'Unespecified',
  'Data_size_Mb': 90,
  'Species': 'Mus musculus',
  'Data_curator': None},
 {'id': '18060',
  'General_description': 'LOX1(L1)',
  'Purpose': 'Strengths and limitations of period estimation methods for circadian data.( TEST )',
  'Description': 'Strengths and limitations of period estimation methods for circadian data.( TEST )',
  'Open_Access': 'under CC_BY license',
  'Comments': None,
  'collection_date': '2021-01-18',
  'Authors': 'Yili Chen,',
  'Institutions/Fundings': 'Sun Yat-Sen University,',
  'Data_category': 'RNA levels (e.g. qRT-PCR)',
  'Technique': 'Unespecified',
  'Technique_details': 'Unespecified',
  'Data_size_Mb': 20,
  'Species': 'Arabidopsis thaliana',
  'Data_curator': None},
 {'id': '14673',
  'General_description': 'Neurospora TF Circadian Clock - 2013Mar08CD',
  'Purpose': 'We are trying to identify novel transcriptional networks controlling the clock in N. crassa, using a reverse genetic screen based on luminescent circadian reporters and a Neurospora Knockout collection of transcription factors.',
  'Description': 'The strains analyzed in this experiment are knockouts for the following loci: NCU01145 (xc1077), NCU05022 (xc1093), NCU05996 (xc1092), NCU06028 (xc927), NCU07587 (xc1095), , and NCU08063 (xc1064).',
  'Open_Access': 'under CC_BY license',
  'Comments': None,
  'collection_date': '2019-06-12',
  'Authors': 'Felipe Muñoz,',
  'Institutions/Fundings': 'Pontificia Universidad Católica de Chile,',
  'Data_category': 'Expression reporter (e.g. Luc/GFP-imaging)',
  'Technique': 'Luciferase luminescence (Percival incubators equipped with CCD PIXIS 1024B cameras (Princeton Instruments).)',
  'Technique_details': 'To conduct the circadian analyses (see below), spores from the selected progenies were inoculated in a 96 well plate containing LNN-CCD media (LARRONDO et al. 2015; OLIVARES-YANEZ 2015), with 25 μM of Luciferin (GoldBio). Cultures were grown for 24 hours in constant light (LL) at 25˚C and then were analyzed under free-running conditions; consisting of constant darkness (DD) and 25˚C, for 4 to 5 days in Percival incubators equipped with CCD PIXIS 1024B cameras (Princeton Instruments). The acquired datasets varied in some cases containing 2 or 3 pictures per hour, with exposition times of 10 or 5 minutes respectively, a difference that does not affect the analyses as information can be compared throughout the datasets. Importantly, control wild type (WT) strains were included in each 96-well plate and in each experimental run.',
  'Data_size_Mb': 50,
  'Species': 'Neurospora crassa',
  'Data_curator': None},
 {'id': '14680',
  'General_description': 'Neurospora TF Circadian Clock - 2012Jun15BC',
  'Purpose': 'We are trying to identify novel transcriptional networks controlling the clock in N. crassa, using a reverse genetic screen based on luminescent circadian reporters and a Neurospora Knockout collection of transcription factors.',
  'Description': 'The strains analyzed in this experiment are knockouts for the following loci: NCU04848 (xc555), NCU04866 (xc551), NCU05242 (xc594), NCU06186 (xc596), NCU08999 (xc553), , and NCU09529 (xc547).',
  'Open_Access': 'under CC_BY license',
  'Comments': None,
  'collection_date': '2019-06-13',
  'Authors': 'Felipe Muñoz,',
  'Institutions/Fundings': 'Pontificia Universidad Católica de Chile,',
  'Data_category': 'Expression reporter (e.g. Luc/GFP-imaging)',
  'Technique': 'Luciferase luminescence (Percival incubators equipped with CCD PIXIS 1024B cameras (Princeton Instruments).)',
  'Technique_details': 'To conduct the circadian analyses (see below), spores from the selected progenies were inoculated in a 96 well plate containing LNN-CCD media (LARRONDO et al. 2015; OLIVARES-YANEZ 2015), with 25 μM of Luciferin (GoldBio). Cultures were grown for 24 hours in constant light (LL) at 25˚C and then were analyzed under free-running conditions; consisting of constant darkness (DD) and 25˚C, for 4 to 5 days in Percival incubators equipped with CCD PIXIS 1024B cameras (Princeton Instruments). The acquired datasets varied in some cases containing 2 or 3 pictures per hour, with exposition times of 10 or 5 minutes respectively, a difference that does not affect the analyses as information can be compared throughout the datasets. Importantly, control wild type (WT) strains were included in each 96-well plate and in each experimental run.',
  'Data_size_Mb': 50,
  'Species': 'Neurospora crassa',
  'Data_curator': None},
 {'id': '13830',
  'General_description': 'Activity DLAN',
  'Purpose': '3 nights of DLAN on activity rhythms in males and females',
  'Description': None,
  'Open_Access': 'under CC_BY license',
  'Comments': None,
  'collection_date': '2019-06-18',
  'Authors': 'William Walker,',
  'Institutions/Fundings': 'West Virginia University,',
  'Data_category': 'Behaviour (e.g. wheel running)',
  'Technique': 'Computer simulation',
  'Technique_details': 'Unespecified',
  'Data_size_Mb': 20,
  'Species': 'Mus musculus',
  'Data_curator': None},
 {'id': '12730734291594',
  'General_description': 'AT0005 4x SD-3xLL',
  'Purpose': 'changes to photoperiod',
  'Description': 'alternate 4 days SD followed by 3 days constant light',
  'Open_Access': 'under CC_BY license',
  'Comments': 'null Growth conditions: LD 6:18 22c; const. 22C W: LD 06:00:18:00 Experimental conditions: AT0005 4x SD-3xLL; const. 22C B+R: 4*LD 06:00:18:00; 3*LL',
  'collection_date': '2006-02-06',
  'Authors': 'Adrian Thomson, Andrew Millar,',
  'Institutions/Fundings': 'University of Edinburgh,',
  'Data_category': 'Expression reporter (e.g. Luc/GFP-imaging)',
  'Technique': 'Luciferase luminescence (HAM 1)',
  'Technique_details': 'imaging script starts 5 minutes before required ZT, then 55 minutes interval, 5 minutes light off, 30 minutes capture sprayed upon transfer from entrainment',
  'Data_size_Mb': 60,
  'Species': 'Arabidopsis thaliana',
  'Data_curator': 'Sarah Hodge,'},
 {'id': '14937',
  'General_description': 'MMTV Sleep',
  'Purpose': 'Circadian Disruption During Sleep. Tumor-bearing mice display altered circadian rhythms in sleep.',
  'Description': None,
  'Open_Access': 'under CC_BY license',
  'Comments': None,
  'collection_date': '2019-08-19',
  'Authors': 'William Walker,',
  'Institutions/Fundings': 'West Virginia University,',
  'Data_category': 'Behaviour (e.g. wheel running)',
  'Technique': 'General imaging',
  'Technique_details': 'Unespecified',
  'Data_size_Mb': 30,
  'Species': 'Mus musculus',
  'Data_curator': None}]

In [5]:
df = pd.json_normalize(data)

In [6]:
sample_data = []
for sample in data['Experiment']:
    sample_info = {'id': sample['id'],
                   'General_description': sample['General_description'],
                   'Purpose': sample['Purpose'],
                   'Description': sample['Description'], 
                   'Open_Access': sample['Open_Access'],
                   'Comments': sample['Comments'],
                   'collection_date': sample['collection_date'],
                   'Authors': sample['Authors'],
                   'Institutions/Fundings': sample['Institutions/Fundings'],
                   'Data_category': sample['Data_category'],
                   'Technique': sample['Technique'],
                   'Technique_details':sample['Technique_details'] ,
                   'Data_size_Mb': sample['Data_size_Mb'],
                   'Species': sample['Species'],
                   'Data_curator': sample['Data_curator']
                  }
    sample_data.append(sample_info)

# Convert the list of dictionaries to a DataFrame
df = pd.DataFrame(sample_data)

# Display the DataFrame
df

,id,General_description,Purpose,Description,Open_Access,Comments,collection_date,Authors,Institutions/Fundings,Data_category,Technique,Technique_details,Data_size_Mb,Species,Data_curator
0,26940,identify zebrafish pld6 as a novel germline-sp...,The supernatants obtained from the two low-spe...,Remove the medium from the cells and wash the ...,under CC_BY license,Mitochondria preparation from cell Glassware a...,2023-11-10,ma dongcheng,"suda,",Behaviour (e.g. wheel running),Other,Unespecified,10,Danio rerio,None
1,19235,Role of PRR7 in control of the CCA1 promoter,To test whether PRR7 is required for circadian...,In previous experiments several clock mutation...,under CC_BY license,Details are as in Bordage et al (2016) New Phy...,2021-05-20,"Hugh Nimmo,","University of Glasgow, BBSRC [BB/K006835/1]",Expression reporter (e.g. Luc/GFP-imaging),Luciferase luminescence (Photek 225/18 CCD cam...,Mature plants were on square vertical agar pla...,50,Arabidopsis thaliana,None
2,17264,CCA1:LUC,Analysis CCA1:LUC period and amplitude changes...,None,under CC_BY license,None,2020-11-11,"Flash Light,","University of Edinburgh,",Expression reporter (e.g. Luc/GFP-imaging),Luciferase luminescence,Unespecified,30,Arabidopsis thaliana,None
3,22843,"Figure 3/5 - Cry1-Luc + pSyn1.Cry1(TAG)::EGFP,...","McManus et al, Figure 3: Translational switchi...",Cry1-Luc SCN transduced with pSyn1.Cry1(TAG)::...,under CC_BY license,None,2022-05-25,"David McManus,","MRC LMB,",Expression reporter (e.g. Luc/GFP-imaging),Luciferase luminescence,Unespecified,90,Mus musculus,None
4,18060,LOX1(L1),Strengths and limitations of period estimation...,Strengths and limitations of period estimation...,under CC_BY license,None,2021-01-18,"Yili Chen,","Sun Yat-Sen University,",RNA levels (e.g. qRT-PCR),Unespecified,Unespecified,20,Arabidopsis thaliana,None
5,14673,Neurospora TF Circadian Clock - 2013Mar08CD,We are trying to identify novel transcriptiona...,The strains analyzed in this experiment are kn...,under CC_BY license,None,2019-06-12,"Felipe Muñoz,","Pontificia Universidad Católica de Chile,",Expression reporter (e.g. Luc/GFP-imaging),Luciferase luminescence (Percival incubators e...,"To conduct the circadian analyses (see below),...",50,Neurospora crassa,None
6,14680,Neurospora TF Circadian Clock - 2012Jun15BC,We are trying to identify novel transcriptiona...,The strains analyzed in this experiment are kn...,under CC_BY license,None,2019-06-13,"Felipe Muñoz,","Pontificia Universidad Católica de Chile,",Expression reporter (e.g. Luc/GFP-imaging),Luciferase luminescence (Percival incubators e...,"To conduct the circadian analyses (see below),...",50,Neurospora crassa,None
7,13830,Activity DLAN,3 nights of DLAN on activity rhythms in males ...,None,under CC_BY license,None,2019-06-18,"William Walker,","West Virginia University,",Behaviour (e.g. wheel running),Computer simulation,Unespecified,20,Mus musculus,None
8,12730734291594,AT0005 4x SD-3xLL,changes to photoperiod,alternate 4 days SD followed by 3 days constan...,under CC_BY license,null Growth conditions: LD 6:18 22c; const. 22...,2006-02-06,"Adrian Thomson, Andrew Millar,","University of Edinburgh,",Expression reporter (e.g. Luc/GFP-imaging),Luciferase luminescence (HAM 1),imaging script starts 5 minutes before require...,60,Arabidopsis thaliana,"Sarah Hodge,"
9,14937,MMTV Sleep,Circadian Disruption During Sleep. Tumor-beari...,None,under CC_BY license,None,2019-08-19,"William Walker,","West Virginia University,",Behaviour (e.g. wheel running),General imaging,Unespecified,30,Mus musculus,None

In [7]:
df.dtypes

id                       object
General_description      object
Purpose                  object
Description              object
Open_Access              object
Comments                 object
collection_date          object
Authors                  object
Institutions/Fundings    object
Data_category            object
Technique                object
Technique_details        object
Data_size_Mb              int64
Species                  object
Data_curator             object
dtype: object

In [8]:
df.duplicated().sum()

0

In [9]:
def missing_values_table(df): 
        mis_val = df.isnull().sum()
        mis_val_percent = 100 * df.isnull().sum()/len(df)
        mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
        mis_val_table_ren_columns = mis_val_table.rename(
        columns = {0 : 'Missing Values', 1 : '% of Total Values'})
        return mis_val_table_ren_columns

In [10]:
missing_values_table(df)

                       Missing Values  % of Total Values
id                                  0                0.0
General_description                 0                0.0
Purpose                             0                0.0
Description                         3               30.0
Open_Access                         0                0.0
Comments                            7               70.0
collection_date                     0                0.0
Authors                             0                0.0
Institutions/Fundings               0                0.0
Data_category                       0                0.0
Technique                           0                0.0
Technique_details                   0                0.0
Data_size_Mb                        0                0.0
Species                             0                0.0
Data_curator                        9               90.0

In [11]:
profile = ProfileReport(df)
profile

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [12]:
text_cell = df.at[0,'Purpose']
len(text_cell)

326

In [13]:
lista = {}
for sample in data['Experiment']:
    text_cell = df.at[0,'Purpose']
    len(text_cell)

In [14]:
for columna in df.columns:
    print(f'Columna: {columna}')
    print(df[columna])

Columna: id
0             26940
1             19235
2             17264
3             22843
4             18060
5             14673
6             14680
7             13830
8    12730734291594
9             14937
Name: id, dtype: object
Columna: General_description
0    identify zebrafish pld6 as a novel germline-sp...
1         Role of PRR7 in control of the CCA1 promoter
2                                             CCA1:LUC
3    Figure 3/5 - Cry1-Luc + pSyn1.Cry1(TAG)::EGFP,...
4                                             LOX1(L1)
5          Neurospora TF Circadian Clock - 2013Mar08CD
6          Neurospora TF Circadian Clock - 2012Jun15BC
7                                        Activity DLAN
8                                    AT0005 4x SD-3xLL
9                                           MMTV Sleep
Name: General_description, dtype: object
Columna: Purpose
0    The supernatants obtained from the two low-spe...
1    To test whether PRR7 is required for circadian...
2    Analysis CCA1:LUC period and amplitude changes...
3    McManus et al, Figure 3: Translational switchi...
4    Strengths and limitations of period estimation...
5    We are trying to identify novel transcriptiona...
6    We are trying to identify novel transcriptiona...
7    3 nights of DLAN on activity rhythms in males ...
8                               changes to photoperiod
9    Circadian Disruption During Sleep. Tumor-beari...
Name: Purpose, dtype: object
Columna: Description
0    Remove the medium from the cells and wash the ...
1    In previous experiments several clock mutation...
2                                                 None
3    Cry1-Luc SCN transduced with pSyn1.Cry1(TAG)::...
4    Strengths and limitations of period estimation...
5    The strains analyzed in this experiment are kn...
6    The strains analyzed in this experiment are kn...
7                                                 None
8    alternate 4 days SD followed by 3 days constan...
9                                                 None
Name: Description, dtype: object
Columna: Open_Access
0    under CC_BY license
1    under CC_BY license
2    under CC_BY license
3    under CC_BY license
4    under CC_BY license
5    under CC_BY license
6    under CC_BY license
7    under CC_BY license
8    under CC_BY license
9    under CC_BY license
Name: Open_Access, dtype: object
Columna: Comments
0    Mitochondria preparation from cell Glassware a...
1    Details are as in Bordage et al (2016) New Phy...
2                                                 None
3                                                 None
4                                                 None
5                                                 None
6                                                 None
7                                                 None
8    null Growth conditions: LD 6:18 22c; const. 22...
9                                                 None
Name: Comments, dtype: object
Columna: collection_date
0    2023-11-10
1    2021-05-20
2    2020-11-11
3    2022-05-25
4    2021-01-18
5    2019-06-12
6    2019-06-13
7    2019-06-18
8    2006-02-06
9    2019-08-19
Name: collection_date, dtype: object
Columna: Authors
0                      ma dongcheng
1                       Hugh Nimmo,
2                      Flash Light,
3                    David McManus,
4                        Yili Chen,
5                     Felipe Muñoz,
6                     Felipe Muñoz,
7                   William Walker,
8    Adrian Thomson, Andrew Millar,
9                   William Walker,
Name: Authors, dtype: object
Columna: Institutions/Fundings
0                                          suda,
1    University of Glasgow, BBSRC [BB/K006835/1]
2                       University of Edinburgh,
3                                       MRC LMB,
4                        Sun Yat-Sen University,
5      Pontificia Universidad Católica de Chile,
6      Pontificia Universidad Católica de Chile,
7                      West Virginia University,
8                       University of Edinburgh,
9                      West Virginia University,
Name: Institutions/Fundings, dtype: object
Columna: Data_category
0                Behaviour (e.g. wheel running)
1    Expression reporter (e.g. Luc/GFP-imaging)
2    Expression reporter (e.g. Luc/GFP-imaging)
3    Expression reporter (e.g. Luc/GFP-imaging)
4                     RNA levels (e.g. qRT-PCR)
5    Expression reporter (e.g. Luc/GFP-imaging)
6    Expression reporter (e.g. Luc/GFP-imaging)
7                Behaviour (e.g. wheel running)
8    Expression reporter (e.g. Luc/GFP-imaging)
9                Behaviour (e.g. wheel running)
Name: Data_category, dtype: object
Columna: Technique
0                                                Other
1    Luciferase luminescence (Photek 225/18 CCD cam...
2                              Luciferase luminescence
3                              Luciferase luminescence
4                                         Unespecified
5    Luciferase luminescence (Percival incubators e...
6    Luciferase luminescence (Percival incubators e...
7                                  Computer simulation
8                      Luciferase luminescence (HAM 1)
9                                      General imaging
Name: Technique, dtype: object
Columna: Technique_details
0                                         Unespecified
1    Mature plants were on square vertical agar pla...
2                                         Unespecified
3                                         Unespecified
4                                         Unespecified
5    To conduct the circadian analyses (see below),...
6    To conduct the circadian analyses (see below),...
7                                         Unespecified
8    imaging script starts 5 minutes before require...
9                                         Unespecified
Name: Technique_details, dtype: object
Columna: Data_size_Mb
0    10
1    50
2    30
3    90
4    20
5    50
6    50
7    20
8    60
9    30
Name: Data_size_Mb, dtype: int64
Columna: Species
0             Danio rerio
1    Arabidopsis thaliana
2    Arabidopsis thaliana
3            Mus musculus
4    Arabidopsis thaliana
5       Neurospora crassa
6       Neurospora crassa
7            Mus musculus
8    Arabidopsis thaliana
9            Mus musculus
Name: Species, dtype: object
Columna: Data_curator
0            None
1            None
2            None
3            None
4            None
5            None
6            None
7            None
8    Sarah Hodge,
9            None
Name: Data_curator, dtype: object

In [15]:
df.columns

Index(['id', 'General_description', 'Purpose', 'Description', 'Open_Access',
       'Comments', 'collection_date', 'Authors', 'Institutions/Fundings',
       'Data_category', 'Technique', 'Technique_details', 'Data_size_Mb',
       'Species', 'Data_curator'],
      dtype='object')

In [23]:
df

,id,General_description,Purpose,Description,Open_Access,Comments,collection_date,Authors,Institutions/Fundings,Data_category,Technique,Technique_details,Data_size_Mb,Species,Data_curator,Len_General_description
0,26940,identify zebrafish pld6 as a novel germline-sp...,The supernatants obtained from the two low-spe...,Remove the medium from the cells and wash the ...,under CC_BY license,Mitochondria preparation from cell Glassware a...,2023-11-10,ma dongcheng,"suda,",Behaviour (e.g. wheel running),Other,Unespecified,10,Danio rerio,None,86
1,19235,Role of PRR7 in control of the CCA1 promoter,To test whether PRR7 is required for circadian...,In previous experiments several clock mutation...,under CC_BY license,Details are as in Bordage et al (2016) New Phy...,2021-05-20,"Hugh Nimmo,","University of Glasgow, BBSRC [BB/K006835/1]",Expression reporter (e.g. Luc/GFP-imaging),Luciferase luminescence (Photek 225/18 CCD cam...,Mature plants were on square vertical agar pla...,50,Arabidopsis thaliana,None,44
2,17264,CCA1:LUC,Analysis CCA1:LUC period and amplitude changes...,None,under CC_BY license,None,2020-11-11,"Flash Light,","University of Edinburgh,",Expression reporter (e.g. Luc/GFP-imaging),Luciferase luminescence,Unespecified,30,Arabidopsis thaliana,None,8
3,22843,"Figure 3/5 - Cry1-Luc + pSyn1.Cry1(TAG)::EGFP,...","McManus et al, Figure 3: Translational switchi...",Cry1-Luc SCN transduced with pSyn1.Cry1(TAG)::...,under CC_BY license,None,2022-05-25,"David McManus,","MRC LMB,",Expression reporter (e.g. Luc/GFP-imaging),Luciferase luminescence,Unespecified,90,Mus musculus,None,56
4,18060,LOX1(L1),Strengths and limitations of period estimation...,Strengths and limitations of period estimation...,under CC_BY license,None,2021-01-18,"Yili Chen,","Sun Yat-Sen University,",RNA levels (e.g. qRT-PCR),Unespecified,Unespecified,20,Arabidopsis thaliana,None,8
5,14673,Neurospora TF Circadian Clock - 2013Mar08CD,We are trying to identify novel transcriptiona...,The strains analyzed in this experiment are kn...,under CC_BY license,None,2019-06-12,"Felipe Muñoz,","Pontificia Universidad Católica de Chile,",Expression reporter (e.g. Luc/GFP-imaging),Luciferase luminescence (Percival incubators e...,"To conduct the circadian analyses (see below),...",50,Neurospora crassa,None,43
6,14680,Neurospora TF Circadian Clock - 2012Jun15BC,We are trying to identify novel transcriptiona...,The strains analyzed in this experiment are kn...,under CC_BY license,None,2019-06-13,"Felipe Muñoz,","Pontificia Universidad Católica de Chile,",Expression reporter (e.g. Luc/GFP-imaging),Luciferase luminescence (Percival incubators e...,"To conduct the circadian analyses (see below),...",50,Neurospora crassa,None,43
7,13830,Activity DLAN,3 nights of DLAN on activity rhythms in males ...,None,under CC_BY license,None,2019-06-18,"William Walker,","West Virginia University,",Behaviour (e.g. wheel running),Computer simulation,Unespecified,20,Mus musculus,None,13
8,12730734291594,AT0005 4x SD-3xLL,changes to photoperiod,alternate 4 days SD followed by 3 days constan...,under CC_BY license,null Growth conditions: LD 6:18 22c; const. 22...,2006-02-06,"Adrian Thomson, Andrew Millar,","University of Edinburgh,",Expression reporter (e.g. Luc/GFP-imaging),Luciferase luminescence (HAM 1),imaging script starts 5 minutes before require...,60,Arabidopsis thaliana,"Sarah Hodge,",17
9,14937,MMTV Sleep,Circadian Disruption During Sleep. Tumor-beari...,None,under CC_BY license,None,2019-08-19,"William Walker,","West Virginia University,",Behaviour (e.g. wheel running),General imaging,Unespecified,30,Mus musculus,None,10

In [25]:
lista={0,1,2,3,4,5,6,7,8,9}
totales = []
for value in lista:
    valor = len(df["General_description"][value])
    totales.append(valor)

In [26]:
totales

[86, 44, 8, 56, 8, 43, 43, 13, 17, 10]

In [27]:
df['Len_General_description']= totales

In [28]:
totales

[86, 44, 8, 56, 8, 43, 43, 13, 17, 10]

In [29]:
totales = []
for value in lista:
    valor = len(df["Description"][value])
    totales.append(valor)

TypeError: object of type 'NoneType' has no len()

In [34]:
totales1 = []
for value in lista:
    valor = len(df["Purpose"][value])
    totales1.append(valor)

In [35]:
df["Len_Purpose"] = totales1

In [36]:
df

,id,General_description,Purpose,Description,Open_Access,Comments,collection_date,Authors,Institutions/Fundings,Data_category,Technique,Technique_details,Data_size_Mb,Species,Data_curator,Len_General_description,Len_Purpose
0,26940,identify zebrafish pld6 as a novel germline-sp...,The supernatants obtained from the two low-spe...,Remove the medium from the cells and wash the ...,under CC_BY license,Mitochondria preparation from cell Glassware a...,2023-11-10,ma dongcheng,"suda,",Behaviour (e.g. wheel running),Other,Unespecified,10,Danio rerio,None,86,326
1,19235,Role of PRR7 in control of the CCA1 promoter,To test whether PRR7 is required for circadian...,In previous experiments several clock mutation...,under CC_BY license,Details are as in Bordage et al (2016) New Phy...,2021-05-20,"Hugh Nimmo,","University of Glasgow, BBSRC [BB/K006835/1]",Expression reporter (e.g. Luc/GFP-imaging),Luciferase luminescence (Photek 225/18 CCD cam...,Mature plants were on square vertical agar pla...,50,Arabidopsis thaliana,None,44,93
2,17264,CCA1:LUC,Analysis CCA1:LUC period and amplitude changes...,None,under CC_BY license,None,2020-11-11,"Flash Light,","University of Edinburgh,",Expression reporter (e.g. Luc/GFP-imaging),Luciferase luminescence,Unespecified,30,Arabidopsis thaliana,None,8,57
3,22843,"Figure 3/5 - Cry1-Luc + pSyn1.Cry1(TAG)::EGFP,...","McManus et al, Figure 3: Translational switchi...",Cry1-Luc SCN transduced with pSyn1.Cry1(TAG)::...,under CC_BY license,None,2022-05-25,"David McManus,","MRC LMB,",Expression reporter (e.g. Luc/GFP-imaging),Luciferase luminescence,Unespecified,90,Mus musculus,None,56,166
4,18060,LOX1(L1),Strengths and limitations of period estimation...,Strengths and limitations of period estimation...,under CC_BY license,None,2021-01-18,"Yili Chen,","Sun Yat-Sen University,",RNA levels (e.g. qRT-PCR),Unespecified,Unespecified,20,Arabidopsis thaliana,None,8,82
5,14673,Neurospora TF Circadian Clock - 2013Mar08CD,We are trying to identify novel transcriptiona...,The strains analyzed in this experiment are kn...,under CC_BY license,None,2019-06-12,"Felipe Muñoz,","Pontificia Universidad Católica de Chile,",Expression reporter (e.g. Luc/GFP-imaging),Luciferase luminescence (Percival incubators e...,"To conduct the circadian analyses (see below),...",50,Neurospora crassa,None,43,227
6,14680,Neurospora TF Circadian Clock - 2012Jun15BC,We are trying to identify novel transcriptiona...,The strains analyzed in this experiment are kn...,under CC_BY license,None,2019-06-13,"Felipe Muñoz,","Pontificia Universidad Católica de Chile,",Expression reporter (e.g. Luc/GFP-imaging),Luciferase luminescence (Percival incubators e...,"To conduct the circadian analyses (see below),...",50,Neurospora crassa,None,43,227
7,13830,Activity DLAN,3 nights of DLAN on activity rhythms in males ...,None,under CC_BY license,None,2019-06-18,"William Walker,","West Virginia University,",Behaviour (e.g. wheel running),Computer simulation,Unespecified,20,Mus musculus,None,13,57
8,12730734291594,AT0005 4x SD-3xLL,changes to photoperiod,alternate 4 days SD followed by 3 days constan...,under CC_BY license,null Growth conditions: LD 6:18 22c; const. 22...,2006-02-06,"Adrian Thomson, Andrew Millar,","University of Edinburgh,",Expression reporter (e.g. Luc/GFP-imaging),Luciferase luminescence (HAM 1),imaging script starts 5 minutes before require...,60,Arabidopsis thaliana,"Sarah Hodge,",17,22
9,14937,MMTV Sleep,Circadian Disruption During Sleep. Tumor-beari...,None,under CC_BY license,None,2019-08-19,"William Walker,","West Virginia University,",Behaviour (e.g. wheel running),General imaging,Unespecified,30,Mus musculus,None,10,97

#### Number of characters per cell

In [37]:
def character_long (new_list, row_header, number_of_elements):
    for value in number_of_elements:
        valor = len(df[row_header][value])
        new_list.append(valor)
    return new_list

In [38]:
new_list = []
row_header = "General_description"
number_of_entrance = {0,1,2,3,4,5,6,7,8,9}

In [39]:
general_description_chracters_lengh = character_long(new_list, row_header, number_of_entrance)

In [40]:
general_description_chracters_lengh

[86, 44, 8, 56, 8, 43, 43, 13, 17, 10]

#### Number of words per cells

In [42]:
lista = []

In [43]:
def number_of_words (row_header, number_of_elements, df,lista):
    for value in number_of_elements:
        phrase = df[row_header][value]
        words_test = count_words(phrase)
        lista.append(words_test)
    return lista

In [44]:
general_description_number_words = number_of_words(row_header,number_of_entrance,df,lista)
general_description_number_words

[11, 9, 1, 8, 1, 6, 6, 2, 3, 2]

In [45]:
phrase = df['General_description'][0]
words_test = count_words(phrase)
words_test

11

#### Appliance to the whole data frame

In [48]:
header = "General_description"
for index, row in df.items():
    word_counts = Counter(row[header].split())
    most_common_words = word_counts.most_common()

KeyError: 'General_description'

In [49]:
header_list = df.columns.to_list()
header_list

['id',
 'General_description',
 'Purpose',
 'Description',
 'Open_Access',
 'Comments',
 'collection_date',
 'Authors',
 'Institutions/Fundings',
 'Data_category',
 'Technique',
 'Technique_details',
 'Data_size_Mb',
 'Species',
 'Data_curator',
 'Len_General_description',
 'Len_Purpose']

#### New profile

In [50]:
profile_len = ProfileReport(df)
profile_len

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [28]:
text = df['General_description'][0]
text

'identify zebrafish pld6 as a novel germline-specific gene by cross-analyzing different'

In [30]:
character_counts = Counter(text)
character_counts

Counter({'e': 10,
         ' ': 10,
         'i': 8,
         'n': 7,
         'f': 5,
         'a': 5,
         's': 5,
         'r': 4,
         'l': 4,
         'd': 3,
         'y': 3,
         'g': 3,
         'c': 3,
         't': 2,
         'z': 2,
         'b': 2,
         'p': 2,
         'o': 2,
         '-': 2,
         'h': 1,
         '6': 1,
         'v': 1,
         'm': 1})

In [35]:
# To count unique words per entrance
words = text.split()
words_count = Counter(words)
len(words_count)

11

In [36]:
def count_words(phrase):
    words = phrase.split()
    return len(words)

In [38]:
phrase = df['General_description'][0]
words_test = count_words(phrase)
words_test

11